"""Environment-backed configuration for the EduNova agent.

All limits are server-side and bounded again here so an accidental environment
value cannot turn the agent into an unbounded worker.

LLM_PROVIDER modes
------------------
- ``local`` (default): self-hosted GGUF model running in-process through
  llama.cpp (``llama-cpp-python``). No external LLM provider, no API key.
  This is the actual AI brain: planning, reasoning and final answers are all
  generated by the local quantized model.
- ``openai_compatible`` (legacy/manual override): any OpenAI-compatible HTTP
  endpoint. ``http://`` is only accepted for private/loopback hosts (for
  example a self-hosted gateway on the same private network); public hosts
  must use https.
- ``openai`` (legacy/manual override): the original external OpenAI default,
  kept only for emergency rollback after the local model is verified.
"""

from __future__ import annotations

from dataclasses import dataclass
import ipaddress
import os
from pathlib import Path
import re
from urllib.parse import urlsplit


def _integer(name: str, default: int, minimum: int, maximum: int) -> int:
    try:
        value = int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        value = default
    return max(minimum, min(value, maximum))


def _floating(name: str, default: float, minimum: float, maximum: float) -> float:
    try:
        value = float(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        value = default
    return max(minimum, min(value, maximum))


def _boolean(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _cgroup_memory_limit() -> int | None:
    """Return the container memory limit when cgroup v2 exposes one."""
    try:
        raw = open("/sys/fs/cgroup/memory.max", encoding="utf-8").read().strip()
        return None if raw == "max" else int(raw)
    except (OSError, ValueError):
        return None


def _clean_env_value(raw: str | None) -> str:
    """Strip whitespace and surrounding quotes without exposing secrets."""
    if raw is None:
        return ""
    value = str(raw).strip()
    if not value:
        return ""
    iteration = 0
    while len(value) >= 2 and value[0] in "\"'`" and value[-1] in "\"'`" and iteration < 5:
        inner = value[1:-1].strip()
        if inner == value:
            break
        value = inner
        iteration += 1
    value = value.strip().strip("\"'`").strip()
    return value


def _first_env(*names: str, default: str = "") -> str:
    """Return first non-empty cleaned env value among aliases, else default."""
    for name in names:
        raw = os.getenv(name)
        if raw is None:
            continue
        cleaned = _clean_env_value(raw)
        if cleaned:
            return cleaned
        continue
    return _clean_env_value(default) if default else ""


def _normalize_base_url(raw: str) -> str:
    """Normalize LLM base URL to a safe, deduplicated form."""
    cleaned = _clean_env_value(raw)
    if not cleaned:
        return "https://api.openai.com/v1"

    cleaned = cleaned.strip()
    if " " in cleaned or "\n" in cleaned or "\t" in cleaned:
        cleaned = "".join(cleaned.split())

    cleaned = cleaned.rstrip("/")
    lower = cleaned.lower()
    if lower.endswith("/chat/completions"):
        cleaned = cleaned[: -len("/chat/completions")].rstrip("/")
    elif lower.endswith("/chat/completion"):
        cleaned = cleaned[: -len("/chat/completion")].rstrip("/")

    if "://" in cleaned:
        proto, rest = cleaned.split("://", 1)
        proto = proto.lower() + "://"
        while "//" in rest:
            rest = rest.replace("//", "/")
        cleaned = proto + rest
    else:
        rest = cleaned
        while "//" in rest:
            rest = rest.replace("//", "/")
        cleaned = rest

    while "/v1/v1" in cleaned:
        cleaned = cleaned.replace("/v1/v1", "/v1")
    cleaned = cleaned.rstrip("/")

    if not cleaned.startswith("http://") and not cleaned.startswith("https://"):
        cleaned = "https://" + cleaned.lstrip("/")

    cleaned = cleaned.rstrip("/")
    if cleaned in ("https://", "http://", ""):
        return "https://api.openai.com/v1"
    return cleaned


def _is_private_or_loopback_host(host: str) -> bool:
    """True for localhost / private-network hosts (self-hosted gateways only)."""
    host = (host or "").strip("[]").lower().rstrip(".")
    if not host:
        return False
    if host in {"localhost", "localhost.localdomain"} or host.endswith(
        (".internal", ".local", ".localhost", ".lan", ".home")
    ):
        return True
    try:
        ip = ipaddress.ip_address(host)
    except ValueError:
        return False
    return not ip.is_global


_LOCAL_MODEL_ID_SAFE = re.compile(r"[^A-Za-z0-9._/:-]+")

# -----------------------------------------------------------------------------
# Verified self-hosted model catalogue.
#
# Every entry below was verified against the HuggingFace repository file tree
# (``/api/models/<repo>/tree/main``): the file exists on ``resolve/main``, is
# public/ungated, and the recorded ``sha256``/``bytes`` come from the LFS
# metadata of that exact revision. This registry is what prevents a repeat of
# the HTTP 404 outage: the shipped default is a file that provably exists, and
# an operator override is integrity-checked for free when it is a known file.
#
# ``ram_mb`` is a conservative estimate of resident memory for weights + KV
# cache + llama.cpp compute buffers at the default context size, i.e. what the
# Render instance must have on top of ~130MB of Python/FastAPI overhead.
# -----------------------------------------------------------------------------
KNOWN_MODELS: dict[tuple[str, str], dict[str, object]] = {
    # Default. Qwen2.5-0.5B-Instruct: Apache-2.0, ChatML, 32k context, trained
    # for instruction following AND tool calling — the smallest model in this
    # family that still writes usable educational explanations.
    ("bartowski/Qwen2.5-0.5B-Instruct-GGUF", "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf"): {
        "sha256": "6eb923e7d26e9cea28811e1a8e852009b21242fb157b26149d3b188f3a8c8653",
        "bytes": 397_808_192,
        "chat_format": "chatml",
        "ram_mb": 700,
    },
    ("bartowski/Qwen2.5-0.5B-Instruct-GGUF", "Qwen2.5-0.5B-Instruct-IQ4_XS.gguf"): {
        "sha256": "df178ccd68e24ce0c74f957765c00e8f5eec5c51216a1acd4444202e58df6cc1",
        "bytes": 349_402_688,
        "chat_format": "chatml",
        "ram_mb": 650,
    },
    ("bartowski/Qwen2.5-0.5B-Instruct-GGUF", "Qwen2.5-0.5B-Instruct-Q8_0.gguf"): {
        "sha256": "25130a98aa782284a7dabea0c23245b2fd371ed47244e79d78b8ec23245fdf96",
        "bytes": 531_068_480,
        "chat_format": "chatml",
        "ram_mb": 850,
    },
    # Lowest-RAM option (SmolLM2-360M-Instruct, Apache-2.0, ChatML). Weaker
    # reasoning, but it boots inside a 512MB instance.
    ("bartowski/SmolLM2-360M-Instruct-GGUF", "SmolLM2-360M-Instruct-Q4_K_M.gguf"): {
        "sha256": "2fa3f013dcdd7b99f9b237717fa0b12d75bbb89984cc1274be1471a465bac9c2",
        "bytes": 270_590_880,
        "chat_format": "chatml",
        "ram_mb": 480,
    },
    # Quality upgrade for a 2GB+ instance.
    ("bartowski/Qwen2.5-1.5B-Instruct-GGUF", "Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"): {
        "sha256": "1adf0b11065d8ad2e8123ea110d1ec956dab4ab038eab665614adba04b6c3370",
        "bytes": 986_048_768,
        "chat_format": "chatml",
        "ram_mb": 1500,
    },
}

DEFAULT_LOCAL_MODEL_REPO = "bartowski/Qwen2.5-0.5B-Instruct-GGUF"
DEFAULT_LOCAL_MODEL_FILE = "Qwen2.5-0.5B-Instruct-Q4_K_M.gguf"

# -----------------------------------------------------------------------------
# Verified self-hosted PyTorch (transformers) model catalogue.
#
# These are the *model ids* the PyTorch-first runtime downloads through
# HuggingFace at service startup (never during a user request).  ``params`` is
# the approximate parameter count used by adaptive compute to pick a dtype that
# fits the container memory; ``ctx`` is the practical context ceiling to set
# via LOCAL_MODEL_CTX on the target instance.
#
# Model selection rule (do NOT confuse model size with intelligence):
# choose the strongest model that can realistically operate within the
# available infrastructure; capability is then added via tools + retrieval +
# memory + EduNova data + web research, not by inflating the prompt.
# -----------------------------------------------------------------------------
TORCH_KNOWN_MODELS: dict[str, dict[str, object]] = {
    # Default PyTorch model. Qwen2.5-0.5B-Instruct: Apache-2.0, ChatML + native
    # tool-calling training, 32k native context, strong multilingual coverage
    # (English/Tamil/Hindi + many others) — the smallest Qwen2.5 that still
    # produces usable educational explanations and JSON decisions.
    "Qwen/Qwen2.5-0.5B-Instruct": {
        "params": 494_000_000,
        "ctx": 8192,
        "default_dtype": "auto",
        "min_ram_mb": 2048,
        "recommended_ram_mb": 4096,
    },
    # Quality upgrade once the instance has room (4GB+): still small enough for
    # shared CPU, dramatically better reasoning/coding.
    "Qwen/Qwen2.5-1.5B-Instruct": {
        "params": 1_540_000_000,
        "ctx": 8192,
        "default_dtype": "auto",
        "min_ram_mb": 4096,
        "recommended_ram_mb": 8192,
    },
    # Lower-RAM option (SmolLM2-360M-Instruct, Apache-2.0, ChatML). Weaker
    # reasoning and weak multilingual support — last resort for tiny instances.
    "HuggingFaceTB/SmolLM2-360M-Instruct": {
        "params": 362_000_000,
        "ctx": 4096,
        "default_dtype": "auto",
        "min_ram_mb": 2048,
        "recommended_ram_mb": 2048,
    },
}

DEFAULT_TORCH_MODEL_REPO = "Qwen/Qwen2.5-0.5B-Instruct"


def torch_model_entry(repo: str) -> dict[str, object] | None:
    return TORCH_KNOWN_MODELS.get(str(repo or "").strip())


def torch_params_for_repo(repo: str) -> int:
    entry = torch_model_entry(repo)
    try:
        return int(entry.get("params", 0)) if entry else 0
    except (TypeError, ValueError):
        return 0



def known_model_entry(repo: str, filename: str) -> dict[str, object] | None:
    return KNOWN_MODELS.get((str(repo or "").strip(), str(filename or "").strip()))


def catalogue_files_for_repo(repo: str) -> list[str]:
    """All verified filenames registered for ``repo`` (may be empty)."""
    repo = str(repo or "").strip()
    return [filename for (entry_repo, filename) in KNOWN_MODELS if entry_repo == repo]


def catalogue_default_file_for_repo(repo: str) -> str | None:
    """The verified default GGUF filename for a known repository, else None.

    Used by the runtime's self-healing path: when an operator-provided
    ``LOCAL_MODEL_FILE`` provably does not exist in a repository we know
    (HTTP 404 preflight), the verified default for that same repo is applied
    instead of leaving the service permanently down. Returns ``None`` for
    repositories we have never verified, where no safe default exists.
    """
    repo = str(repo or "").strip()
    if not repo:
        return None
    if repo == DEFAULT_LOCAL_MODEL_REPO:
        return DEFAULT_LOCAL_MODEL_FILE
    files = catalogue_files_for_repo(repo)
    return files[0] if files else None


def _sanitize_public_url(raw: str) -> str:
    """Strip credentials and query strings so a URL is safe to log/expose.

    HuggingFace ``resolve`` links are public, but a custom ``LOCAL_MODEL_URL``
    may embed basic-auth credentials or a signed query token; neither may ever
    reach a log line, a health payload, or the browser.
    """
    value = str(raw or "").strip()
    if not value:
        return ""
    try:
        parts = urlsplit(value)
    except Exception:
        return "invalid-url"
    if not parts.hostname:
        return "invalid-url"
    port = f":{parts.port}" if parts.port else ""
    path = parts.path or "/"
    suffix = "?<redacted>" if parts.query else ""
    return f"{parts.scheme or 'https'}://{parts.hostname}{port}{path}{suffix}"


@dataclass(frozen=True, slots=True)
class Settings:
    # Provider selection. "local" = self-hosted GGUF model via llama.cpp.
    llm_provider: str = "local"
    llm_api_key: str = ""
    llm_model: str = "gpt-4.1-mini"  # legacy/external providers only
    llm_base_url: str = "https://api.openai.com/v1"
    llm_timeout_seconds: int = 60
    llm_max_output_tokens: int = 2048
    llm_temperature: float = 0.2
    llm_json_mode: bool = True

    # ---- Self-hosted local model (llama.cpp) -------------------------------
    # The default is a file that is VERIFIED to exist on HuggingFace (see
    # KNOWN_MODELS above). Qwen2.5-0.5B-Instruct @ Q4_K_M is ~380MiB of
    # weights: small enough for a 2GB Render Standard instance, strong enough
    # for instruction following, multi-turn context and JSON/tool decisions.
    local_model_repo: str = DEFAULT_LOCAL_MODEL_REPO
    local_model_file: str = DEFAULT_LOCAL_MODEL_FILE
    local_model_url: str = ""  # optional direct download URL override
    local_model_dir: str = "./models_cache"
    local_model_sha256: str = ""  # optional checksum verification
    local_model_expected_bytes: int = 0  # optional exact-size verification
    # Floor below which a "model" is assumed to be an error page, not weights.
    # 10MB is right for every real quantized GGUF; only lower it for tests or
    # a deliberately micro model.
    local_model_min_bytes: int = 10 * 1024 * 1024
    local_model_download_retries: int = 3
    local_model_ctx_size: int = 6144
    local_model_threads: int = 2
    local_model_batch: int = 256
    local_model_chat_format: str = "chatml"
    local_preload_model: bool = True
    local_chat_wait_seconds: int = 25  # how long chat waits for warmup before 503
    local_model_download_timeout: int = 900
    local_model_startup_timeout: int = 300
    local_inference_idle_timeout: int = 90

    # ---- Runtime -------------------------------------------------------------
    # The LLM runtime is llama.cpp (GGUF) inside the persistent inference
    # service. PyTorch is used for embeddings/ML only. The legacy "torch" LLM
    # runtime settings below are retained for configuration compatibility.
    local_model_runtime: str = "llama_cpp"
    local_model_dtype: str = "auto"
    local_model_device: str = "auto"  # auto | cpu | cuda
    local_model_hf_revision: str = "main"
    local_model_trust_remote_code: bool = False
    # "off" by default: torch.compile on small shared CPUs costs more than it
    # saves for these models. Set "1"/"auto" to benchmark it per instance.
    local_model_torch_compile: str = "off"

    # ---- RAG retrieval (learning material semantic index) ------------------
    rag_enabled: bool = True
    rag_embedding_model: str = ""  # empty => default all-MiniLM-L6-v2 (auto fallback)
    rag_persist_dir: str = ""  # empty => <LOCAL_MODEL_DIR>/rag

    web_search_api_key: str = ""
    web_search_provider: str = "brave"
    web_search_max_results: int = 5
    web_request_timeout_seconds: int = 10
    web_max_content_length: int = 200_000
    web_max_extracted_chars: int = 45_000
    web_max_redirects: int = 5

    max_agent_iterations: int = 5
    max_tool_calls: int = 8
    max_agent_runtime_seconds: int = 180
    agent_max_context_chars: int = 24_000
    conversation_max_turns: int = 12
    conversation_ttl_seconds: int = 86_400

    ai_internal_token: str = ""
    ai_require_internal_token: bool = False
    app_backend_url: str = "http://127.0.0.1:4000"
    # ---- Split architecture: orchestrator -> persistent inference service --
    # The lightweight orchestrator (main.py) never loads the model; it calls
    # the inference service (inference_server.py) at this URL with the shared
    # AI_INTERNAL_TOKEN. Empty => "not configured" (reported, never guessed).
    inference_url: str = ""
    # Network backstop for one generation round-trip (streaming keeps the
    # connection active; this is not an answer-length limit).
    inference_request_timeout: int = 600
    cors_origins: tuple[str, ...] = (
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://edunova-x.ranjitacharya13.workers.dev",
    )

    # ------------------------------------------------------------------ LLM --
    @property
    def is_local_llm(self) -> bool:
        return self.llm_provider == "local"

    @property
    def local_model_id(self) -> str:
        """Safe identifier of the local model (no secrets, no URLs)."""
        if self.local_model_url:
            try:
                parts = urlsplit(self.local_model_url)
                filename = (parts.path.rsplit("/", 1) or [""])[-1]
                return _LOCAL_MODEL_ID_SAFE.sub("", f"{parts.hostname or 'custom'}:{filename}")[:160]
            except Exception:
                return "custom-url-model"
        repo = str(self.local_model_repo or "").strip()
        file = str(self.local_model_file or "").strip()
        if self.local_model_runtime == "torch":
            # The torch runtime loads a whole HF repo / local directory.
            return _LOCAL_MODEL_ID_SAFE.sub("", repo or "torch-model")[:160]
        return _LOCAL_MODEL_ID_SAFE.sub("", f"{repo}:{file}")[:160] if repo else "local-model"

    @property
    def local_model_download_url(self) -> str:
        """The source URL the runtime fetches weights from (diagnostics only).

        - explicit ``LOCAL_MODEL_URL`` (llama.cpp runtime, direct download);
        - torch runtime: the HuggingFace repo page of ``LOCAL_MODEL_REPO``
          (files are downloaded via ``huggingface_hub.snapshot_download``);
        - llama.cpp runtime: canonical ``resolve/main`` link from repo + file.
        """
        if self.local_model_url:
            return self.local_model_url
        if not self.local_model_repo:
            return ""
        if self.local_model_runtime == "torch":
            return f"https://huggingface.co/{self.local_model_repo}"
        if not self.local_model_file:
            return ""
        return (
            f"https://huggingface.co/{self.local_model_repo}"
            f"/resolve/main/{self.local_model_file}"
        )

    @property
    def local_model_safe_url(self) -> str:
        """``local_model_download_url`` with credentials/query stripped."""
        return _sanitize_public_url(self.local_model_download_url)

    @property
    def local_model_known_entry(self) -> dict[str, object] | None:
        """Verified catalogue metadata for the configured repo/file, if any."""
        if self.local_model_url:
            return None
        return known_model_entry(self.local_model_repo, self.local_model_file)

    @property
    def local_model_expected_sha256(self) -> str:
        """Explicit LOCAL_MODEL_SHA256, else the verified catalogue checksum."""
        pinned = (self.local_model_sha256 or "").strip().lower()
        if pinned:
            return pinned
        entry = self.local_model_known_entry
        return str(entry.get("sha256", "")) if entry else ""

    @property
    def local_model_expected_size(self) -> int:
        """Explicit LOCAL_MODEL_BYTES, else the verified catalogue size."""
        if self.local_model_expected_bytes > 0:
            return self.local_model_expected_bytes
        entry = self.local_model_known_entry
        try:
            return int(entry.get("bytes", 0)) if entry else 0
        except (TypeError, ValueError):
            return 0

    @property
    def local_model_estimated_ram_mb(self) -> int:
        """Rough resident-memory need of the configured model (0 = unknown).

        For the llama.cpp (GGUF) runtime this uses catalogue metadata. For the
        PyTorch runtime it estimates from the parameter count and the selected
        dtype (int8 ≈ 1 B/param, bf16 ≈ 2, fp32 ≈ 4) plus ~0.9 GB for the
        torch/transformers runtime, tokenizer, KV cache headroom and FastAPI.
        """
        entry = self.local_model_known_entry
        if entry:
            try:
                return int(entry.get("ram_mb", 0))
            except (TypeError, ValueError):
                return 0
        if self.local_model_runtime == "torch":
            params = torch_params_for_repo(self.local_model_repo)
            if not params:
                return 0
            dtype = str(self.local_model_dtype or "auto").lower()
            bytes_per_param = 1 if dtype == "int8" else (2 if dtype == "bf16" else 4)
            if dtype == "auto":
                bytes_per_param = 1  # adaptive compute defaults to int8 on CPU
            return int(params * bytes_per_param / (1024 * 1024)) + 900
        expected = self.local_model_expected_size
        # weights + ~35% for KV cache, compute buffers and allocator slack.
        return int(expected / (1024 * 1024) * 1.35) if expected else 0

    @property
    def llm_configured(self) -> bool:
        if self.llm_provider == "local":
            return self.llm_configuration_error is None
        return bool(
            self.llm_provider in {"openai", "openai_compatible"}
            and self.llm_api_key
            and self.llm_model
            and self.llm_base_url
            and self.llm_configuration_error is None
        )

    @property
    def llm_configuration_error(self) -> str | None:
        if self.llm_provider == "local":
            if self.local_model_runtime not in {"torch", "llama_cpp"}:
                return "unsupported_runtime"
            if self.local_model_runtime == "torch":
                # The torch runtime loads a HuggingFace repo id or a local
                # directory that already contains a model (config.json).
                repo = str(self.local_model_repo or "").strip()
                local_dir = Path(repo) if repo else None
                if not repo:
                    return "missing_model_source"
                if self.local_model_url:
                    return "unsupported_for_torch_runtime"  # direct URL is GGUF-only
                if str(self.local_model_file or "").lower().endswith(".gguf"):
                    # A GGUF filename with the torch runtime is a config mistake.
                    return "gguf_file_with_torch_runtime"
                if local_dir and local_dir.exists() and not (local_dir / "config.json").exists():
                    return "local_dir_missing_config"
                return None
            # ---- llama.cpp GGUF runtime (legacy) ----
            if not ((self.local_model_repo and self.local_model_file) or self.local_model_url):
                return "missing_model_source"
            if self.local_model_url:
                try:
                    parsed = urlsplit(self.local_model_url)
                except Exception:
                    return "invalid_model_url"
                host = (parsed.hostname or "").lower()
                if not host or parsed.scheme not in {"http", "https"}:
                    return "invalid_model_url"
                if parsed.scheme == "http" and not _is_private_or_loopback_host(host):
                    return "insecure_model_url"
            elif not str(self.local_model_file).lower().endswith(".gguf"):
                # llama.cpp only loads GGUF; catching this at config time keeps
                # the failure out of the request path.
                return "model_file_not_gguf"
            return None
        if self.llm_provider not in {"openai", "openai_compatible"}:
            return "unsupported_provider"
        try:
            parsed = urlsplit(self.llm_base_url)
            host = (parsed.hostname or "").lower()
        except Exception:
            return "invalid_base_url"
        if not host:
            return "invalid_base_url"
        if parsed.scheme == "http" and not _is_private_or_loopback_host(host):
            # Plain HTTP is only acceptable for self-hosted gateways on a
            # private network; public endpoints must be encrypted.
            return "insecure_base_url"
        if parsed.scheme != "https" and parsed.scheme != "http":
            return "invalid_base_url"
        if self.llm_provider == "openai" and host != "api.openai.com":
            return "provider_base_url_mismatch"
        return None

    @property
    def search_configured(self) -> bool:
        return bool(self.web_search_api_key and self.web_search_provider)

    def llm_safe_diagnostics(self) -> dict[str, object]:
        host = ""
        try:
            host = urlsplit(self.llm_base_url).hostname or ""
        except Exception:
            host = "invalid"
        api_key_present = bool(self.llm_api_key)
        base_url_has_chat_completions = "/chat/completions" in (self.llm_base_url or "").lower()
        base_url_has_double_v1 = "/v1/v1" in (self.llm_base_url or "")
        base_url_is_localhost = any(
            token in (self.llm_base_url or "").lower()
            for token in ("localhost", "127.0.0.1", "0.0.0.0", "::1")
        )
        return {
            "configured": self.llm_configured,
            "provider": self.llm_provider,
            "selfHosted": self.is_local_llm,
            "model": self.local_model_id if self.is_local_llm else self.llm_model[:60],
            "apiKeyPresent": api_key_present,
            "apiKeyRequired": not self.is_local_llm,
            "configurationError": self.llm_configuration_error,
            "llm_configured": self.llm_configured,
            "llm_api_key_present": api_key_present,
            "llm_model_present": bool(self.local_model_id if self.is_local_llm else self.llm_model),
            "llm_model": self.local_model_id if self.is_local_llm else self.llm_model[:60],
            "llm_base_url_present": bool(self.llm_base_url),
            "llm_base_url_host": host,
            "llm_base_url_has_chat_completions_suffix": base_url_has_chat_completions,
            "llm_base_url_has_double_v1": base_url_has_double_v1,
            "llm_base_url_is_localhost": base_url_is_localhost,
            "llm_timeout_seconds": self.llm_timeout_seconds,
            "llm_max_output_tokens": self.llm_max_output_tokens,
            "llm_temperature": self.llm_temperature,
            "llm_json_mode": self.llm_json_mode,
            # Local model (self-hosted) diagnostics — no download URLs or secrets.
            "local_model_id": self.local_model_id,
            "local_model_runtime": self.local_model_runtime,
            "local_model_dtype": self.local_model_dtype,
            "local_model_device": self.local_model_device,
            "local_model_torch_compile": self.local_model_torch_compile,
            "local_model_ctx_size": self.local_model_ctx_size,
            "local_model_threads": self.local_model_threads,
            "local_preload_model": self.local_preload_model,
            "local_model_source": "custom_url" if self.local_model_url else "huggingface",
            "local_model_verified_catalogue_entry": self.local_model_known_entry is not None,
            "local_model_integrity_pinned": bool(self.local_model_expected_sha256),
            "local_model_expected_bytes": self.local_model_expected_size or None,
            "local_model_estimated_ram_mb": self.local_model_estimated_ram_mb or None,
        }


def _normalize_runtime(raw: str | None) -> str:
    """Map runtime aliases onto {torch, llama_cpp}."""
    value = _clean_env_value(raw).lower()
    if value in {"gguf", "llamacpp", "llama_cpp", "llama.cpp", "llama-cpp", "llamacpp-python"}:
        return "llama_cpp"
    if value in {"pytorch", "transformers", "hf", "torch"}:
        return "torch"
    return value or "llama_cpp"  # unknown values fail validation; never silently choose a runtime


def _normalize_dtype(raw: str | None) -> str:
    value = _clean_env_value(raw).lower()
    normalized = {
        "fp32": "fp32", "float32": "fp32",
        "bf16": "bf16", "bfloat16": "bf16",
        "int8": "int8", "qint8": "int8", "dynamic-int8": "int8",
        "auto": "auto", "": "auto",
    }
    return normalized.get(value, "auto")


def load_settings() -> Settings:
    cors_raw = _clean_env_value(os.getenv("CORS_ORIGIN", ""))
    cors_origins = tuple(
        origin.strip().rstrip("/")
        for origin in cors_raw.split(",")
        if origin.strip()
    ) or (
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://edunova-x.ranjitacharya13.workers.dev",
    )

    # One canonical configuration contract. Provider-specific aliases are intentionally
    # not accepted: aliases made it possible to send a key for one provider to another.
    llm_provider = _first_env("LLM_PROVIDER", default="local").strip().lower()
    if llm_provider in {"gguf", "llama.cpp", "llamacpp", "selfhosted", "self_hosted", "offline"}:
        llm_provider = "local"
    if llm_provider in {"compatible", "custom"}:
        llm_provider = "openai_compatible"
    llm_api_key = _first_env("LLM_API_KEY")
    llm_model = _first_env("LLM_MODEL", default="gpt-4.1-mini")
    llm_model = _clean_env_value(llm_model) or "gpt-4.1-mini"
    raw_base_url = _first_env(
        "LLM_BASE_URL", default="https://api.openai.com/v1"
    )
    llm_base_url = _normalize_base_url(raw_base_url)

    is_local = llm_provider == "local"

    # Runtime + model source selection.  LOCAL_MODEL_RUNTIME explicitly selects
    # the inference runtime; when it is left unset we fall back to llama_cpp for
    # existing GGUF-based deployments (repo ends with -GGUF or a .gguf file is
    # pinned) so a rollout never silently breaks a working model cache, and to
    # torch otherwise.
    runtime_env = _clean_env_value(os.getenv("LOCAL_MODEL_RUNTIME", ""))
    repo_env = _clean_env_value(os.getenv("LOCAL_MODEL_REPO", ""))
    file_env = _clean_env_value(os.getenv("LOCAL_MODEL_FILE", ""))
    is_gguf_deployment = bool(repo_env.upper().endswith("-GGUF")) or file_env.lower().endswith(".gguf")
    local_runtime = _normalize_runtime(runtime_env if runtime_env else ("llama_cpp" if is_gguf_deployment or not repo_env else "torch"))
    local_dtype = _normalize_dtype(os.getenv("LOCAL_MODEL_DTYPE", "auto"))
    torch_compile = _clean_env_value(os.getenv("LOCAL_MODEL_TORCH_COMPILE", "off")).lower()
    if torch_compile not in {"off", "0", "false", "none", "auto", "1", "true", "on"}:
        torch_compile = "off"

    if local_runtime == "llama_cpp":
        default_repo = DEFAULT_LOCAL_MODEL_REPO
        default_file = DEFAULT_LOCAL_MODEL_FILE
    else:
        default_repo = DEFAULT_TORCH_MODEL_REPO
        default_file = ""

    # Provider-aware defaults: the local model runs on a small shared CPU, so
    # the autonomous loop defaults are tightened to keep single requests fast.
    max_iterations = _integer("MAX_AGENT_ITERATIONS", 5 if is_local else 12, 1, 30)
    max_tools = _integer("MAX_TOOL_CALLS", 8 if is_local else 15, 0, 40)
    # For the local model the agent context must physically fit in the llama.cpp
    # window (roughly 3 chars/token) alongside the system prompt and the output
    # budget, otherwise every rich turn hits the truncation guard.
    max_context = _integer("AGENT_MAX_CONTEXT_CHARS", 12_000 if is_local else 90_000, 4_000, 250_000)
    max_output = _integer("LLM_MAX_OUTPUT_TOKENS", 2048 if is_local else 3000, 128, 12_000)
    # Production previously pinned 512/900 in the Render dashboard. Do not let
    # that stale optimization silently reintroduce incomplete code or lessons.
    if is_local:
        max_output = max(2048, max_output)
    local_ctx = _integer("LOCAL_MODEL_CTX", 6144, 1024, 32768)
    if is_local:
        local_ctx = max(2048, local_ctx)
        # No silent context downgrade on small containers: if the configured
        # model + context do not fit, inference/resources.py fails fast with
        # MODEL_RESOURCE_INSUFFICIENT (required/available/recommended MiB)
        # instead of hiding the problem behind a smaller window.

    app_backend_url = _first_env(
        "APP_BACKEND_URL", "EXPRESS_URL", "SERVER_URL", default="http://127.0.0.1:4000"
    ).rstrip("/")

    threads_env = _clean_env_value(os.getenv("LOCAL_MODEL_THREADS", ""))
    threads_default = 0 if local_runtime == "torch" else 2  # 0 = adaptive auto
    try:
        threads_value = int(threads_env) if threads_env else threads_default
    except (TypeError, ValueError):
        threads_value = threads_default

    return Settings(
        llm_provider=llm_provider,
        llm_api_key=llm_api_key,
        llm_model=llm_model,
        llm_base_url=llm_base_url,
        llm_timeout_seconds=_integer("LLM_REQUEST_TIMEOUT", 60, 5, 300),
        llm_max_output_tokens=max_output,
        llm_temperature=_floating("LLM_TEMPERATURE", 0.2, 0.0, 1.0),
        llm_json_mode=_boolean("LLM_JSON_MODE", True),
        local_model_runtime=local_runtime,
        local_model_dtype=local_dtype,
        local_model_device=_clean_env_value(os.getenv("LOCAL_MODEL_DEVICE", "auto")).lower() or "auto",
        local_model_hf_revision=_clean_env_value(os.getenv("LOCAL_MODEL_REVISION", "main")) or "main",
        local_model_trust_remote_code=_boolean("LOCAL_MODEL_TRUST_REMOTE_CODE", False),
        local_model_torch_compile=torch_compile,
        local_model_repo=_clean_env_value(os.getenv("LOCAL_MODEL_REPO", default_repo)) or default_repo,
        local_model_file=_clean_env_value(os.getenv("LOCAL_MODEL_FILE", default_file)) or default_file,
        local_model_url=_clean_env_value(os.getenv("LOCAL_MODEL_URL", "")),
        local_model_dir=_clean_env_value(os.getenv("LOCAL_MODEL_DIR", "./models_cache")) or "./models_cache",
        local_model_sha256=_clean_env_value(os.getenv("LOCAL_MODEL_SHA256", "")).lower(),
        local_model_expected_bytes=_integer("LOCAL_MODEL_BYTES", 0, 0, 200_000_000_000),
        local_model_min_bytes=_integer("LOCAL_MODEL_MIN_BYTES", 10 * 1024 * 1024, 4096, 20_000_000_000),
        local_model_download_retries=_integer("LOCAL_MODEL_DOWNLOAD_RETRIES", 3, 0, 8),
        local_model_ctx_size=local_ctx,
        local_model_threads=max(0, min(threads_value, 8)),
        local_model_batch=_integer("LOCAL_MODEL_BATCH", 256, 32, 2048),
        local_model_chat_format=_clean_env_value(os.getenv("LOCAL_MODEL_CHAT_FORMAT", "chatml")).lower() or "chatml",
        local_preload_model=_boolean("LOCAL_PRELOAD_MODEL", True),
        local_chat_wait_seconds=_integer("LOCAL_CHAT_WAIT_TIMEOUT", 120, 1, 300),
        local_model_startup_timeout=_integer("MODEL_STARTUP_TIMEOUT", 300, 10, 900),
        local_inference_idle_timeout=_integer("MODEL_INFERENCE_IDLE_TIMEOUT", 90, 15, 300),
        local_model_download_timeout=_integer("LOCAL_MODEL_DOWNLOAD_TIMEOUT", 1800, 60, 7200),
        rag_enabled=_boolean("RAG_ENABLED", True),
        rag_embedding_model=_clean_env_value(os.getenv("RAG_EMBEDDING_MODEL", "")),
        rag_persist_dir=_clean_env_value(os.getenv("RAG_PERSIST_DIR", "")),
        web_search_api_key=_clean_env_value(os.getenv("WEB_SEARCH_API_KEY", "")),
        web_search_provider=_clean_env_value(os.getenv("WEB_SEARCH_PROVIDER", "brave")).lower(),
        web_search_max_results=_integer("WEB_SEARCH_MAX_RESULTS", 5, 1, 10),
        web_request_timeout_seconds=_integer("WEB_REQUEST_TIMEOUT", 10, 2, 30),
        web_max_content_length=_integer("WEB_MAX_CONTENT_LENGTH", 200_000, 10_000, 1_000_000),
        web_max_extracted_chars=_integer("WEB_MAX_EXTRACTED_CHARS", 45_000, 4_000, 100_000),
        web_max_redirects=_integer("WEB_MAX_REDIRECTS", 5, 0, 10),
        max_agent_iterations=max_iterations,
        max_tool_calls=max_tools,
        max_agent_runtime_seconds=_integer("MAX_AGENT_RUNTIME_SECONDS", 180, 30, 900),
        agent_max_context_chars=max_context,
        conversation_max_turns=_integer("CONVERSATION_MAX_TURNS", 12, 2, 30),
        conversation_ttl_seconds=_integer("CONVERSATION_TTL_SECONDS", 86_400, 300, 604_800),
        ai_internal_token=_clean_env_value(os.getenv("AI_INTERNAL_TOKEN", "")),
        ai_require_internal_token=_boolean("AI_REQUIRE_INTERNAL_TOKEN", False),
        app_backend_url=app_backend_url,
        inference_url=_first_env("AI_INFERENCE_URL", "INFERENCE_SERVICE_URL", default="").rstrip("/"),
        inference_request_timeout=_integer("AI_INFERENCE_REQUEST_TIMEOUT", 600, 15, 3600),
        cors_origins=cors_origins,
    )
