"""FastAPI entrypoint for the EduNova unified autonomous AI agent.

EduNova AI is self-hosted by default: a quantized open-source GGUF model
(Qwen2.5-0.5B-Instruct by default) runs in-process through llama.cpp and acts
as the actual AI brain. No OpenAI/Groq/Gemini/Anthropic/OpenRouter calls are
made. Web search stays available as an external *data source*; every answer is
reasoned over and generated by the local model.
"""

from __future__ import annotations

import asyncio
from contextlib import asynccontextmanager
import json
import logging
import os
from pathlib import Path
import secrets
import time
from typing import Any
from datetime import datetime, timezone
from urllib.parse import urlsplit

from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field

# Local development convenience only. Production injects environment variables.
try:
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent / ".env")
    load_dotenv(Path(__file__).resolve().parents[1] / "server" / ".env")
except ImportError:
    pass

from agent.engine import AgentEngine
from agent.llm import LLMConfigurationError, LLMResponseError
from agent.local_llm import (
    create_llm,
    runtime_available_for,
    runtime_version_for,
)
from agent.memory import ConversationStore
from agent.router import FAST_INTENTS, IntentRouter, run_fast_path
from agent.tools import ToolRegistry, build_all_tools
from config import load_settings, torch_params_for_repo

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("edunova.api")
settings = load_settings()


# ---------------------------------------------------------------------------
# Observability: request ids + production metrics (no secrets ever).
# ---------------------------------------------------------------------------
def _new_request_id() -> str:
    return secrets.token_hex(16)


_METRICS: dict[str, Any] = {
    "request_count": 0,
    "success_count": 0,
    "error_count": 0,
    "model_load_time_ms": None,
    "cold_start_time_ms": None,
    "first_token_latency_ms": None,
    "generation_time_ms": None,
    "tokens_generated": 0,
    "tokens_per_second": None,
    "tool_latency_ms": 0.0,
    "database_latency_ms": 0.0,
    "web_latency_ms": 0.0,
    "total_request_latency_ms": 0.0,
    "queue_time_ms": 0.0,
    "request_count_by_intent": {},
    "model_memory_usage_bytes": None,
    "cpu_usage_percent": None,
    "started_at": datetime.now(timezone.utc).isoformat(),
    "latency_count": 0,
}


def _bump_metric(key: str, amount: float = 1.0) -> None:
    try:
        _METRICS[key] = float(_METRICS.get(key) or 0.0) + amount
    except (TypeError, ValueError):
        pass


def _record_latency(metric_key: str, milliseconds: float) -> None:
    """Exponential-moving average latency (robust without a histogram lib)."""
    key = f"ema_{metric_key}"
    count_key = f"count_{metric_key}"
    try:
        previous = float(_METRICS.get(key) or 0.0)
        count = int(_METRICS.get(count_key) or 0)
        _METRICS[count_key] = count + 1
        if count == 0:
            _METRICS[key] = float(milliseconds)
        else:
            _METRICS[key] = (0.8 * previous) + (0.2 * float(milliseconds))
    except (TypeError, ValueError):
        pass


def _process_resources() -> dict[str, Any]:
    """Best-effort RSS + CPU percent (no psutil dependency)."""
    rss_bytes = None
    try:
        with open(f"/proc/{os.getpid()}/status", encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("VmRSS:"):
                    rss_bytes = int(line.split()[1]) * 1024
                    break
    except (OSError, ValueError):
        pass
    cpu_percent = None
    try:
        with open("/proc/stat", encoding="utf-8") as handle:
            first = [int(value) for value in handle.readline().split()[1:]]
        time.sleep(0.05)
        with open("/proc/stat", encoding="utf-8") as handle:
            second = [int(value) for value in handle.readline().split()[1:]]
        delta = sum(second) - sum(first)
        if delta > 0:
            idle_delta = (second[3] - first[3]) + (second[4] - first[4])
            cpu_percent = round(min(100.0, max(0.0, (1 - idle_delta / delta) * 100.0)), 2)
    except (OSError, ValueError, IndexError):
        pass
    return {"rssBytes": rss_bytes, "cpuPercent": cpu_percent}


# --- Safe startup diagnostics (no secrets) ---
def _log_startup_diagnostics() -> None:
    diag = settings.llm_safe_diagnostics()
    host = diag.get("llm_base_url_host") or "unknown"
    is_prod = os.getenv("NODE_ENV", "").lower() == "production" or os.getenv("ENV", "").lower() == "production"
    localhost_warning = ""
    if diag.get("llm_base_url_is_localhost") and is_prod and not settings.is_local_llm:
        localhost_warning = " [WARNING: base_url points to localhost in production]"
    logger.info(
        "AI_SERVICE_STARTUP llm_configured=%s provider=%s model=%s api_key_present=%s search_configured=%s internal_auth_required=%s%s",
        diag.get("llm_configured"),
        settings.llm_provider,
        diag.get("llm_model") or "none",
        diag.get("llm_api_key_present"),
        settings.search_configured,
        settings.ai_require_internal_token,
        localhost_warning,
    )
    if settings.is_local_llm:
        if settings.llm_configured:
            logger.info(
                "LOCAL_MODEL_STARTUP runtime=%s model=%s dtype=%s device=%s ctx=%s threads=%s preload=%s dir=%s",
                settings.local_model_runtime,
                settings.local_model_id,
                settings.local_model_dtype,
                settings.local_model_device,
                settings.local_model_ctx_size,
                settings.local_model_threads,
                settings.local_preload_model,
                settings.local_model_dir,
            )
            # Requirement: the resolved download URL must be visible in the
            # production logs. It is sanitized (no credentials, no query) so it
            # is safe to print, and it is what makes a future 404 diagnosable
            # in one glance instead of a guessing game.
            logger.info(
                "LOCAL_MODEL_SOURCE url=%s expected_bytes=%s sha256_pinned=%s est_ram_mb=%s",
                settings.local_model_safe_url or "not-configured",
                settings.local_model_expected_size or "unknown",
                bool(settings.local_model_expected_sha256),
                settings.local_model_estimated_ram_mb or "unknown",
            )
            torch_known = (
                settings.local_model_runtime == "torch"
                and bool(torch_params_for_repo(settings.local_model_repo))
            )
            if not settings.local_model_known_entry and not settings.local_model_url and not torch_known:
                logger.warning(
                    "LOCAL_MODEL_NOT_IN_VERIFIED_CATALOGUE runtime=%s repo=%s file=%s "
                    "hint=The file existence/size are not pre-verified; a wrong "
                    "LOCAL_MODEL_REPO will fail startup with a download/404 error. "
                    "Use a catalogue model (default: %s) or add it to the operator catalogue.",
                    settings.local_model_runtime,
                    settings.local_model_repo,
                    settings.local_model_file or "-",
                    settings.local_model_repo,
                )
            # Stale external-provider variables (e.g. a leftover Groq/OpenAI key
            # and base URL) are IGNORED while LLM_PROVIDER=local. They never
            # reach the model path, but leaving them in the dashboard is
            # confusing and keeps a live API key sitting on the service. Values
            # are never logged — only which variable names are present.
            stale_external = [
                name
                for name in ("LLM_API_KEY", "LLM_BASE_URL", "LLM_MODEL")
                if os.getenv(name, "").strip()
            ]
            if stale_external:
                logger.warning(
                    "STALE_EXTERNAL_LLM_ENV detected=%s hint=LLM_PROVIDER=local ignores "
                    "external provider variables; remove %s from the service environment "
                    "(they are unused and only keep credentials deployed)",
                    ",".join(stale_external),
                    ",".join(stale_external),
                )

        else:
            logger.error(
                "LOCAL_MODEL_CONFIGURATION_INCOMPLETE reason=%s url=%s "
                "hint=Set LOCAL_MODEL_REPO/LOCAL_MODEL_FILE or LOCAL_MODEL_URL",
                settings.llm_configuration_error,
                settings.local_model_safe_url or "not-configured",
            )
        return
    if not settings.llm_configured:
        missing: list[str] = []
        if not settings.llm_api_key:
            missing.append("LLM_API_KEY")
        if not settings.llm_model:
            missing.append("LLM_MODEL")
        if not settings.llm_base_url:
            missing.append("LLM_BASE_URL")
        logger.warning(
            "AI_LLM_CONFIGURATION_INCOMPLETE missing=%s llm_key_present=%s llm_model_present=%s llm_base_url_present=%s "
            "hint=Self-hosted default: set LLM_PROVIDER=local (recommended) or legacy LLM_PROVIDER/LLM_API_KEY/LLM_MODEL/LLM_BASE_URL",
            ",".join(missing) if missing else "unknown",
            diag.get("llm_api_key_present"),
            diag.get("llm_model_present"),
            diag.get("llm_base_url_present"),
        )
    else:
        logger.info(
            "AI_PROVIDER_STARTUP_OK provider_host=%s model=%s timeout=%s json_mode=%s",
            host,
            settings.llm_model,
            settings.llm_timeout_seconds,
            settings.llm_json_mode,
        )


_log_startup_diagnostics()

registry = ToolRegistry(
    allowed_permissions={"READ_INTERNAL", "WRITE_INTERNAL", "READ_EXTERNAL", "UTILITY"}
)
for definition in build_all_tools(settings):
    registry.register(definition)

# Construction is lightweight; the GGUF model itself is downloaded and loaded
# in the background during the FastAPI lifespan (port binds immediately).
llm, model_manager = create_llm(settings)

agent = AgentEngine(settings, llm, registry)
intent_router = IntentRouter(settings)
provider_runtime = {
    "state": "ready" if settings.llm_configured else "missing_config",
    "lastCheckedAt": None,
    "lastHttpStatus": None,
    "lastErrorType": None,
}
if settings.is_local_llm:
    provider_runtime["state"] = "model_loading" if settings.local_preload_model else "cold"


def _provider_log_host(settings) -> str:
    """Where the completion physically came from, for logs.

    The local provider runs in-process, so echoing `llm_base_url` (a leftover
    external-API setting) would name a host that was never contacted.
    """
    if settings.is_local_llm:
        return "in-process:llama.cpp"
    try:
        return urlsplit(settings.llm_base_url).hostname or "none" if settings.llm_base_url else "none"
    except Exception:
        return "invalid"


def _set_provider_state(state: str, status: int | None = None, error_type: str | None = None) -> None:
    provider_runtime.update({
        "state": state,
        "lastCheckedAt": datetime.now(timezone.utc).isoformat(),
        "lastHttpStatus": status,
        "lastErrorType": error_type,
    })


conversations = ConversationStore(
    max_turns=settings.conversation_max_turns,
    ttl_seconds=settings.conversation_ttl_seconds,
)


# ---------------------------------------------------------------------------
# RAG retrieval service (semantic index for EduNova learning material).
# ---------------------------------------------------------------------------
def _default_rag_persist_dir() -> Path:
    raw = Path(settings.rag_persist_dir) if settings.rag_persist_dir else Path(settings.local_model_dir) / "rag"
    if raw.is_absolute():
        return raw
    return Path(__file__).resolve().parent / raw


rag_index: Any = None
if settings.rag_enabled:
    try:
        from inference.rag import Embedder, RagIndex  # noqa: PLC0415

        embedder = Embedder(settings.rag_embedding_model or None)
        persist = _default_rag_persist_dir()
        rag_index = RagIndex(embedder=embedder, persist_dir=str(persist))
        rag_index.load()
        logger.info("RAG_INDEX_READY persist=%s owners=%s chunks=%s", persist, rag_index.stats.get("owners"), rag_index.stats.get("chunks"))
    except Exception as exc:  # noqa: BLE001 — RAG must never block the AI service
        rag_index = None
        logger.error("RAG_INDEX_UNAVAILABLE reason=%s", str(exc)[:200])


@asynccontextmanager
async def lifespan(app: FastAPI):
    # The model lifecycle starts HERE, before any user traffic: the weights are
    # downloaded (once, into the persistent cache), loaded and warmed to READY
    # in the background while the port is already bound. A normal user request
    # therefore never triggers a download/load — if it arrives during this
    # boot window it is queued (with an honest "preparing" status) until the
    # model becomes READY, then processed. See /api/ai/ready + /health.
    if model_manager is not None and settings.local_preload_model:
        if not runtime_available_for(settings):
            logger.error(
                "LOCAL_MODEL_RUNTIME_MISSING runtime=%s hint=install the runtime for this "
                "provider (LOCAL_MODEL_RUNTIME=%s): pip install -r ai_engine/requirements.txt",
                settings.local_model_runtime,
                settings.local_model_runtime,
            )
        else:
            logger.info(
                "LOCAL_MODEL_RUNTIME runtime=%s version=%s",
                settings.local_model_runtime,
                runtime_version_for(settings),
            )
        model_manager.ensure_loading()
    yield


app = FastAPI(
    title="EduNova AI Agent",
    version="4.0.0",
    description=(
        "Self-hosted unified data-aware learning and research agent. PyTorch-first "
        "inference runtime (torch.inference_mode + transformers, quantized when "
        "appropriate) reasoning over the EduNova database, web research, RAG "
        "retrieval and conversation memory. The model is downloaded and warmed to "
        "READY at service startup; user requests are queued during warm-up and "
        "never trigger a model download."
    ),
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.cors_origins),
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "X-AI-Internal-Token"],
)


class ChatRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    message: str = Field(min_length=1, max_length=12_000)
    conversation_id: str | None = Field(default=None, alias="conversationId", max_length=100)
    owner_id: str | None = Field(default=None, alias="ownerId", max_length=200)
    user_role: str | None = Field(default="student", alias="userRole", max_length=50)
    user_name: str | None = Field(default="Student", alias="userName", max_length=100)
    user_email: str | None = Field(default=None, alias="userEmail", max_length=320)
    email: str | None = Field(default=None, max_length=320)  # Legacy client compatibility.
    application_context: dict[str, Any] = Field(default_factory=dict, alias="applicationContext")
    stream: bool = False
    request_id: str | None = Field(default=None, alias="requestId", max_length=80)
    client_started_at: float | None = Field(default=None, exclude=True)


@app.get("/")
async def root() -> dict[str, Any]:
    return {
        "success": True,
        "service": "edunova-agent",
        "version": "4.0.0",
        "architecture": (
            "self-hosted unified data-aware agent "
            f"(runtime={settings.local_model_runtime} + IntentRouter + ToolRegistry + web research + RAG)"
        ),
        "endpoint": "POST /api/ai/chat",
    }


def _model_health_block(include_source: bool = False) -> dict[str, Any]:
    if model_manager is None:
        return {}
    return {"model": model_manager.snapshot(include_source=include_source)}


def _model_state_value() -> str:
    """Legacy lowercase model state (the value existing health UIs key off)."""
    if settings.is_local_llm and model_manager is not None:
        return str(getattr(model_manager, "state", "unknown") or "unknown")
    return str(provider_runtime.get("state") or "unknown")


def _model_lifecycle_value() -> str:
    """Canonical lifecycle name when the runtime exposes one."""
    if settings.is_local_llm and model_manager is not None:
        lifecycle = getattr(model_manager, "lifecycle", None)
        if lifecycle is not None:
            return str(getattr(lifecycle, "state", "UNKNOWN"))
    return _model_state_value().upper()


def _model_is_ready() -> bool:
    """True only when the model is READY *and* a live runtime handle exists.

    Prefers the runtime's authoritative ``is_ready()`` (set only after a
    successful warm-up inference). The previous ``state == "ready"`` check was
    unreliable: the generation path resets ``state`` to "ready" around every
    call, so a model whose warm-up had FAILED still reported ready here — which
    is precisely how /api/ai/ready returned 200 for a model that could not
    answer, and why the gateway forwarded requests that then timed out.
    """
    if not settings.is_local_llm or model_manager is None:
        return provider_runtime["state"] == "ready"
    is_ready = getattr(model_manager, "is_ready", None)
    if callable(is_ready):
        try:
            return bool(is_ready())
        except Exception:  # noqa: BLE001 — never let a probe break health
            return False
    return (
        getattr(model_manager, "state", "") == "ready"
        and (
            getattr(model_manager, "_model", None) is not None
            or getattr(model_manager, "_llama", None) is not None
        )
    )


def _runtime_resources() -> dict[str, Any]:
    """Safe cgroup/process sizing data for production capacity diagnostics."""
    memory_limit = None
    cpu_quota = None
    try:
        raw = Path("/sys/fs/cgroup/memory.max").read_text().strip()
        if raw != "max":
            memory_limit = int(raw)
    except (OSError, ValueError):
        pass
    try:
        quota_raw, period_raw = Path("/sys/fs/cgroup/cpu.max").read_text().split()[:2]
        if quota_raw != "max":
            cpu_quota = round(int(quota_raw) / int(period_raw), 2)
    except (OSError, ValueError, ZeroDivisionError):
        pass
    rss_bytes = None
    try:
        import resource

        # Linux ru_maxrss is KiB.
        rss_bytes = int(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss) * 1024
    except (ImportError, OSError, ValueError):
        pass
    return {
        "memoryLimitBytes": memory_limit,
        "processMaxRssBytes": rss_bytes,
        "cpuQuotaCores": cpu_quota,
        "visibleCpuCount": os.cpu_count(),
        "configuredThreads": settings.local_model_threads,
    }


def _readiness() -> dict[str, Any]:
    """The four facts requirement 11 asks a health check to confirm."""
    if not settings.is_local_llm or model_manager is None:
        return {
            "modelFileExists": None,
            "runtimeAvailable": None,
            "modelInitialized": provider_runtime["state"] == "ready",
            "inferenceAvailable": provider_runtime["state"] == "ready",
        }
    snap = model_manager.snapshot()
    ready = _model_is_ready()
    return {
        "modelFileExists": bool(snap.get("fileExists")),
        "runtimeAvailable": bool(snap.get("runtimeAvailable")),
        # Both derive from the manager's authoritative readiness flag, never
        # from the coarse `state` string (which the generation path mutates).
        "modelInitialized": ready,
        "inferenceAvailable": ready,
        "tokenizerLoaded": bool(snap.get("tokenizerLoaded")),
        "modelLoaded": bool(snap.get("modelLoaded")),
        "warmupComplete": bool(snap.get("warmupComplete")),
    }


@app.get("/health")
async def health() -> dict[str, Any]:
    """Liveness for the platform health check.

    Deliberately reports ``status: live`` as soon as the port is bound (Render
    would otherwise kill the service while the weights download), but the model
    readiness is reported honestly next to it so nothing downstream can claim
    "ready" while the model is still starting.
    """
    diag = settings.llm_safe_diagnostics()
    readiness = _readiness()
    payload = {
        "status": "live",
        "service": "edunova-agent",
        "version": "4.0.0",
        # For the self-hosted provider the live state is the model manager's
        # state machine (downloading/loading/warming/ready/error), not a cached
        # probe. "live" (port bound) is intentionally different from "ready".
        "providerState": _model_state_value(),
        "modelLifecycle": _model_lifecycle_value(),
        "modelReady": bool(readiness["modelInitialized"] and readiness["inferenceAvailable"]),
        "readyForTraffic": _model_is_ready(),
        "readiness": readiness,
        "provider": settings.llm_provider,
        "runtime": settings.local_model_runtime,
        "selfHosted": settings.is_local_llm,
        "llmConfigured": settings.llm_configured,
        "llmDiagnostics": diag,
        "webSearchConfigured": settings.search_configured,
        "runtimeResources": _runtime_resources(),
        "internalAuthConfigured": bool(settings.ai_internal_token),
        "internalAuthRequired": settings.ai_require_internal_token,
        # True when the configured LOCAL_MODEL_FILE was rejected by the source
        # host (HTTP 404/410) and the verified catalogue default was applied.
        "configOverrideRejected": bool(
            settings.is_local_llm
            and model_manager is not None
            and model_manager.config_override_rejected
        ),
        "tools": [spec["name"] for spec in registry.specs()],
        "fastPathIntents": sorted(FAST_INTENTS),
        "limits": {
            "maxIterations": settings.max_agent_iterations,
            "maxToolCalls": settings.max_tool_calls,
            "maxRuntimeSeconds": settings.max_agent_runtime_seconds,
        },
    }
    payload.update(_model_health_block())
    return payload


@app.get("/ready")
async def ready() -> Any:
    """Kubernetes/Render-style readiness probe (unauthenticated, minimal).

    ``{"ready": true}`` with HTTP 200 **only** when the model is loaded, the
    tokenizer is loaded and the warm-up inference succeeded. Anything else is
    HTTP 503 — this endpoint must never claim readiness for a model that cannot
    actually serve a request.
    """
    is_ready = _model_is_ready()
    if is_ready:
        return {"ready": True}
    return JSONResponse(status_code=503, content={"ready": False, "state": _model_state_value()})


@app.get("/model/status")
async def model_status() -> dict[str, Any]:
    """Detailed, honest model lifecycle status (safe for operators/UI)."""
    if not settings.is_local_llm or model_manager is None:
        return {
            "status": "external_provider",
            "model_loaded": provider_runtime["state"] == "ready",
            "tokenizer_loaded": False,
            "warmup_complete": provider_runtime["state"] == "ready",
        }
    snap = model_manager.snapshot()
    ready = _model_is_ready()
    lifecycle = _model_lifecycle_value()
    return {
        "status": "ready" if ready else lifecycle.lower(),
        "lifecycle": lifecycle,
        "model_loaded": bool(snap.get("modelLoaded")),
        "tokenizer_loaded": bool(snap.get("tokenizerLoaded")),
        "warmup_complete": bool(snap.get("warmupComplete")),
        "model": settings.local_model_id,
        "runtime": settings.local_model_runtime,
        "dtype": snap.get("dtype"),
        "device": snap.get("device"),
        "modelLoadMs": snap.get("modelLoadMs"),
        "warmupMs": snap.get("warmupMs"),
        "coldStartMs": snap.get("coldStartMs"),
        "tokensPerSecond": snap.get("tokensPerSecond"),
        "parameterEstimate": snap.get("parameterEstimate"),
        "resources": _runtime_resources(),
        # Honest failure reporting — never hidden behind a generic message.
        "error": None if ready else (snap.get("lastError") or None),
        "errorStage": None if ready else (snap.get("errorDetail") or None),
        "retryInSeconds": snap.get("retryInSeconds"),
        "loadFailures": snap.get("loadFailures"),
    }


@app.get("/api/ai/model/status")
async def api_model_status() -> dict[str, Any]:
    """Namespaced alias of /model/status (same payload)."""
    return await model_status()


@app.get("/api/ai/health")
async def ai_health(
    x_ai_internal_token: str | None = Header(default=None),
    deep: bool = False,
) -> dict[str, Any]:
    """Real health check for the model.

    Confirms, in this order: the runtime is importable, the model file exists,
    the model initialized, and inference is available. ``?deep=true`` proves
    the last point by generating a handful of real tokens instead of trusting
    the state machine.
    """
    _authorize_internal_request(x_ai_internal_token)
    probe_state = "skipped"
    probe_error: str | None = None
    probe_detail: dict[str, Any] | None = None
    if deep or not settings.is_local_llm:
        try:
            if settings.is_local_llm and model_manager is not None:
                await llm.probe(deep=True)
                probe_detail = {"inference": "verified"}
            else:
                await llm.probe()
            probe_state = "ready"
            if not settings.is_local_llm:
                _set_provider_state("ready", 200, None)
        except Exception as exc:
            probe_state = "error"
            probe_error = getattr(exc, "error_type", None) or exc.__class__.__name__
            if settings.is_local_llm:
                _set_provider_state(
                    "model_loading" if probe_error == "model_loading" else "model_unavailable",
                    503,
                    probe_error,
                )
            else:
                _safe_error(exc)
    readiness = _readiness()
    if settings.is_local_llm:
        model_ready = (
            model_manager is not None
            and model_manager.state == "ready"
            and (probe_state != "error")
        )
        model_status = model_manager.state if model_manager is not None else "missing_manager"
    else:
        model_ready = provider_runtime["state"] == "ready"
        model_status = provider_runtime["state"]
    payload: dict[str, Any] = {
        "success": model_ready,
        "status": model_status,
        # Single field the UI keys off: only "ready" may render "Ready to help".
        "modelState": model_status,
        "modelReady": model_ready,
        "readiness": readiness,
        "serviceAvailable": True,
        "configured": settings.llm_configured,
        "provider": settings.llm_provider,
        "selfHosted": settings.is_local_llm,
        # Effective model id: after a config-override fallback this reflects
        # the file actually loaded, not the rejected environment value.
        "model": (
            model_manager.settings.local_model_id
            if (settings.is_local_llm and model_manager is not None)
            else (settings.local_model_id if settings.is_local_llm else settings.llm_model)
        ),
        "configOverrideRejected": bool(
            settings.is_local_llm and model_manager is not None and model_manager.config_override_rejected
        ),
        "apiKeyPresent": bool(settings.llm_api_key),
        "configurationError": settings.llm_configuration_error,
        "probe": probe_state,
        "probeError": probe_error,
        "probeDetail": probe_detail,
        "lastCheckedAt": provider_runtime["lastCheckedAt"],
        "lastProviderHttpStatus": provider_runtime["lastHttpStatus"],
        "lastProviderErrorType": provider_runtime["lastErrorType"],
    }
    payload.update(_model_health_block(include_source=True))
    return payload


@app.get("/api/ai/model/source-check")
async def model_source_check(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Verify the configured model URL is really downloadable (HEAD only).

    This is the operator tool for the failure that caused this incident: it
    answers "does LOCAL_MODEL_FILE actually exist?" without downloading 380MB
    and without restarting the service.
    """
    _authorize_internal_request(x_ai_internal_token)
    if not settings.is_local_llm or model_manager is None:
        return {"success": False, "reason": "not_local_provider", "provider": settings.llm_provider}
    try:
        check = await model_manager.preflight()
        return {
            "success": True,
            "model": settings.local_model_id,
            "url": settings.local_model_safe_url,
            **check,
        }
    except Exception as exc:
        report = getattr(exc, "report", None)
        return {
            "success": False,
            "model": settings.local_model_id,
            "url": settings.local_model_safe_url,
            "error": report() if callable(report) else {"reason": str(exc)[:200]},
        }


@app.get("/api/ai/diagnostics")
async def diagnostics(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    _authorize_internal_request(x_ai_internal_token)
    diag = settings.llm_safe_diagnostics()
    host = diag.get("llm_base_url_host") or "unknown"
    base_url_ok = bool(host and host != "unknown" and "." in host)
    return {
        "success": True,
        "service": "edunova-agent",
        "runtime": settings.local_model_runtime,
        "llm": diag,
        "baseUrlResolvable": base_url_ok,
        "resources": _runtime_resources(),
        "estimatedRamMb": settings.local_model_estimated_ram_mb,
        "note": (
            "Self-hosted local model by default (LLM_PROVIDER=local, "
            f"LOCAL_MODEL_RUNTIME={settings.local_model_runtime}); no external LLM API key is required. "
            "Legacy providers remain available behind explicit LLM_PROVIDER=openai[_compatible] configuration."
        ),
    }


@app.get("/api/ai/ready")
async def ai_ready(
    x_ai_internal_token: str | None = Header(default=None),
) -> Any:
    """True readiness gate used by the API gateway request queue.

    Returns HTTP 200 **only** when the model is loaded, the runtime is
    functional AND the warm-up inference succeeded (state READY). Anything else
    returns HTTP 503 with an honest machine-readable reason so the gateway can
    keep the user's request queued instead of dropping it with a vague error.
    """
    _authorize_internal_request(x_ai_internal_token)
    # A readiness poll is also the wake-up signal: when the model is simply not
    # scheduled yet (cold, scale-to-zero or preload=false), kick the single-
    # flight load pipeline so the gateway's request queue does not deadlock
    # waiting for a model nobody started. The poll still answers 503 until the
    # model is actually READY (loaded + warmed), so the queue keeps polling.
    if settings.is_local_llm and model_manager is not None:
        # Force the wake even with preload disabled (torch runtime); the llama
        # runtime's ensure_loading takes no arguments and starts on its own.
        # ensure_loading() is single-flight AND backoff-guarded in the runtime,
        # so this poll can no longer relaunch a failed load pipeline every 2
        # seconds (which previously turned one startup fault into an endless
        # load/OOM thrash that never converged on READY).
        if settings.local_model_runtime == "torch":
            model_manager.ensure_loading(force=True)
        else:
            model_manager.ensure_loading()
    ready = _model_is_ready()
    snap = model_manager.snapshot() if (settings.is_local_llm and model_manager) else {}
    payload: dict[str, Any] = {
        "success": ready,
        "modelReady": ready,
        "modelState": _model_state_value(),
        "lifecycle": _model_lifecycle_value(),
        "runtime": settings.local_model_runtime,
        "model": settings.local_model_id if settings.is_local_llm else "external",
        "readySince": snap.get("loadedAt"),
        "coldStartMs": snap.get("coldStartMs"),
        "lastSelfTest": snap.get("lastSelfTest"),
        "lastError": snap.get("lastError") if not ready else None,
        # Lets the gateway distinguish "still warming, keep queueing" from
        # "startup failed, stop pretending" instead of polling for 10 minutes.
        "errorStage": snap.get("errorDetail") if not ready else None,
        "retryInSeconds": snap.get("retryInSeconds") if not ready else None,
        "permanentFailure": bool(
            not ready
            and isinstance(getattr(model_manager, "error_report", None), dict)
            and model_manager.error_report.get("permanent")
        ),
        "modelLoaded": bool(snap.get("modelLoaded")),
        "tokenizerLoaded": bool(snap.get("tokenizerLoaded")),
        "warmupComplete": bool(snap.get("warmupComplete")),
    }
    if ready:
        return payload
    return JSONResponse(status_code=503, content=payload)


@app.get("/api/ai/metrics")
async def ai_metrics(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Production metrics snapshot (never logs or returns secrets)."""
    _authorize_internal_request(x_ai_internal_token)
    resources = _process_resources()
    snap = model_manager.snapshot() if (settings.is_local_llm and model_manager) else {}
    generation = snap.get("lastGeneration") or {}
    metrics: dict[str, Any] = dict(_METRICS)
    metrics["model_load_time_ms"] = snap.get("coldStartMs") or snap.get("lastSelfTest", {}).get("durationMs")
    metrics["cold_start_time_ms"] = snap.get("coldStartMs")
    metrics["first_token_latency_ms"] = (
        _METRICS.get("first_token_latency_ms")
        or (generation.get("firstTokenMs") if generation else None)
    )
    metrics["generation_time_ms"] = generation.get("durationMs") if generation else _METRICS.get("generation_time_ms")
    metrics["tokens_generated"] = (
        int(_METRICS.get("tokens_generated") or 0)
        + int(generation.get("tokens") or 0)
    )
    metrics["tokens_per_second"] = generation.get("tokensPerSecond") or _METRICS.get("tokens_per_second")
    metrics["model_memory_usage_bytes"] = resources.get("rssBytes")
    metrics["cpu_usage_percent"] = resources.get("cpuPercent")
    metrics["uptime_seconds"] = round(time.time() - (model_manager.started_at or time.time())) if (settings.is_local_llm and model_manager and model_manager.started_at) else None
    metrics["model"] = {
        "runtime": settings.local_model_runtime,
        "state": _model_state_value(),
        "lifecycle": _model_lifecycle_value(),
        "modelId": settings.local_model_id if settings.is_local_llm else None,
    }
    return {"success": True, "metrics": metrics, "resources": resources}


class RagDocumentRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    title: str = Field(min_length=1, max_length=300)
    text: str = Field(min_length=1, max_length=60_000)
    owner_id: str | None = Field(default=None, alias="ownerId", max_length=200)


class RagSearchRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    query: str = Field(min_length=1, max_length=4_000)
    owner_id: str | None = Field(default=None, alias="ownerId", max_length=200)
    k: int = Field(default=5, ge=1, le=10)


def _rag_owner(payload_owner: str | None, header_owner: str | None) -> str:
    """The authenticated server decides the owner — never the model."""
    value = str(payload_owner or header_owner or "").strip()
    if not value or value in {"anonymous", "null", "undefined", "authenticated-user"}:
        return ""
    return value[:200]


@app.get("/api/ai/rag/status")
async def rag_status(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    _authorize_internal_request(x_ai_internal_token)
    if rag_index is None:
        return {"success": False, "enabled": False, "reason": "RAG_ENABLED=false or index failed to start"}
    return {
        "success": True,
        "enabled": True,
        "stats": rag_index.stats,
        "embedderBackend": rag_index.embedder.backend if rag_index.embedder else "none",
        "embeddingModel": rag_index.embedder.model_name if rag_index.embedder else None,
        "persistDir": rag_index.persist_dir,
    }


@app.post("/api/ai/rag/documents")
async def rag_documents(
    payload: RagDocumentRequest,
    x_user_id: str | None = Header(default=None),
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Ingest one document into the authenticated owner's semantic index."""
    _authorize_internal_request(x_ai_internal_token)
    owner = _rag_owner(payload.owner_id, x_user_id)
    if rag_index is None:
        return {"success": False, "error": "RAG is not enabled"}
    if not owner:
        return {"success": False, "error": "authenticated owner identity is required"}
    result = rag_index.ingest_document(owner, payload.title, payload.text)
    result["success"] = bool(result.get("ingested", 0) > 0)
    result["owner"] = owner
    return result


@app.post("/api/ai/rag/search")
async def rag_search(
    payload: RagSearchRequest,
    x_user_id: str | None = Header(default=None),
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Semantic retrieval restricted to the authenticated owner's documents."""
    _authorize_internal_request(x_ai_internal_token)
    owner = _rag_owner(payload.owner_id, x_user_id)
    if rag_index is None:
        return {"success": False, "error": "RAG is not enabled", "results": []}
    if not owner:
        return {"success": False, "error": "authenticated owner identity is required", "results": []}
    results = rag_index.search(owner, payload.query, payload.k)
    return {"success": True, "query": payload.query[:200], "owner": owner, "results": results, "count": len(results)}


@app.get("/api/ai/diagnose")
async def diagnose(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Direct model diagnostic — tests ONLY: model state → inference → response.

    Bypasses AgentEngine, ToolRegistry, MongoDB, web search, and all tools.
    Measures: model load state, inference latency, first-token time, full
    generation time.  Returns structured results so the operator can see
    exactly where the pipeline breaks.
    """
    _authorize_internal_request(x_ai_internal_token)

    started_total = time.monotonic()
    results: dict[str, Any] = {
        "success": False,
        "model": settings.local_model_id if settings.is_local_llm else "external",
        "provider": settings.llm_provider,
    }

    # --- 1. Model state ---
    if model_manager is not None:
        snap = model_manager.snapshot()
        results["modelState"] = snap.get("state", "unknown")
        results["modelReady"] = snap.get("ready", False)
        results["modelFileExists"] = snap.get("fileExists")
        results["fileSizeBytes"] = snap.get("fileSizeBytes")
        results["runtimeAvailable"] = snap.get("runtimeAvailable")
        results["runtimeVersion"] = snap.get("runtimeVersion")
        results["contextSize"] = snap.get("contextSize")
        results["threads"] = snap.get("threads")
        results["lastError"] = snap.get("lastError")
        results["loadedAt"] = snap.get("loadedAt")
    else:
        results["modelState"] = "no_manager"
        results["modelReady"] = False

    # --- 2. Wait for model if not ready ---
    load_wait_ms = 0
    if model_manager is not None and model_manager.state != "ready":
        results["loadAttempted"] = True
        load_started = time.monotonic()
        try:
            await model_manager.wait_ready(timeout=min(60, settings.local_chat_wait_seconds))
            load_wait_ms = int((time.monotonic() - load_started) * 1000)
            results["modelState"] = "ready"
            results["modelReady"] = True
            results["loadWaitMs"] = load_wait_ms
        except Exception as exc:
            load_wait_ms = int((time.monotonic() - load_started) * 1000)
            results["loadWaitMs"] = load_wait_ms
            results["loadError"] = str(exc)[:300]
            results["totalMs"] = int((time.monotonic() - started_total) * 1000)
            return results

    # --- 3. Direct inference test ---
    if not (model_manager is not None and model_manager.state == "ready"):
        results["inferenceSkipped"] = True
        results["inferenceSkipReason"] = "model not ready"
        results["totalMs"] = int((time.monotonic() - started_total) * 1000)
        return results

    inference_started = time.monotonic()
    try:
        text = await llm.complete_text(
            system_prompt="You are EduNova AI.",
            user_prompt="Say hello in one sentence.",
            max_output_tokens=50,
        )
        inference_ms = int((time.monotonic() - inference_started) * 1000)
        results["inferenceResult"] = "SUCCESS"
        results["responseText"] = text[:500]
        results["responseLength"] = len(text)
        results["inferenceMs"] = inference_ms
        results["success"] = True
    except Exception as exc:
        inference_ms = int((time.monotonic() - inference_started) * 1000)
        results["inferenceResult"] = "FAILED"
        results["inferenceError"] = str(exc)[:300]
        results["inferenceMs"] = inference_ms

    results["totalMs"] = int((time.monotonic() - started_total) * 1000)

    # --- 4. Log the diagnostic block ---
    logger.info(
        "[AI DIAGNOSTIC]\n"
        "Model: %s\n"
        "Model state: %s\n"
        "Model loaded: %s\n"
        "Load wait: %s ms\n"
        "Inference: %s\n"
        "Inference time: %s ms\n"
        "Total: %s ms",
        results.get("model"),
        results.get("modelState"),
        results.get("modelReady"),
        load_wait_ms,
        results.get("inferenceResult"),
        results.get("inferenceMs"),
        results.get("totalMs"),
    )

    return results


def _authorize_internal_request(token: str | None) -> None:
    if settings.ai_require_internal_token and not settings.ai_internal_token:
        raise HTTPException(
            status_code=503,
            detail="AI internal authentication is required but not configured",
        )
    if settings.ai_internal_token and not secrets.compare_digest(
        str(token or ""), settings.ai_internal_token
    ):
        raise HTTPException(status_code=401, detail="AI service authorization failed")


def _ms(since: float) -> int:
    """Milliseconds elapsed since a time.monotonic() mark (for stage timings)."""
    return int((time.monotonic() - since) * 1000)


def _owner(request: ChatRequest) -> str:
    return str(request.owner_id or request.email or "anonymous")[:200]


def _sanitize_provider_message_for_user(text: str, limit: int = 180) -> str:
    import re

    t = str(text or "").strip()
    if not t:
        return ""
    t = re.sub(r"<[^>]*>", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    t = re.sub(r"sk-[A-Za-z0-9-_]{10,}", "[redacted]", t)
    if len(t) > limit:
        t = t[:limit].rstrip() + "…"
    return t


def _safe_error(exc: Exception) -> tuple[int, str, str]:
    error_type = str(getattr(exc, "error_type", "") or "")
    # Local self-hosted model states: surface honest, structured states and
    # never substitute a canned/fake answer.
    if error_type == "model_loading":
        # A user request must never see "please try again shortly" while the
        # model is warming. The API gateway queues the request and the client
        # is told it is preparing; this terminal fallback only fires when a
        # direct caller bypassed the gateway's readiness wait.
        _set_provider_state("model_loading", 503, error_type)
        return (
            503,
            "LLM_MODEL_LOADING",
            "EduNova AI is preparing its model — your question is queued and will be answered automatically.",
        )
    if error_type == "model_unavailable":
        _set_provider_state("model_unavailable", 503, error_type)
        # Full, structured diagnostics stay in the backend log (they name the
        # model, the URL and the HTTP status). The browser gets a clean,
        # non-technical sentence — never a raw provider/download error string.
        report = model_manager.error_report if (model_manager is not None) else None
        if report:
            logger.error(
                "MODEL_STARTUP_ERROR model=%s url=%s status=%s stage=%s reason=%s",
                report.get("model"),
                report.get("url"),
                report.get("status"),
                report.get("stage"),
                report.get("reason"),
            )
        else:
            logger.error(
                "MODEL_STARTUP_ERROR model=%s url=%s reason=%s",
                settings.local_model_id,
                settings.local_model_safe_url,
                _sanitize_provider_message_for_user(getattr(exc, "provider_message", "")),
            )
        permanent = bool(report.get("permanent")) if report else False
        if permanent:
            return (
                503,
                "LLM_MODEL_UNAVAILABLE",
                "EduNova AI's self-hosted model is not available on the server. "
                "An administrator needs to check the AI service model configuration.",
            )
        return (
            503,
            "LLM_MODEL_UNAVAILABLE",
            "EduNova AI's self-hosted model could not start. It will retry automatically — "
            "please try again in a moment.",
        )
    if error_type == "deadline_exceeded":
        _set_provider_state("deadline_exceeded", 504, error_type)
        return (
            504,
            "AI_REQUEST_DEADLINE_EXCEEDED",
            "EduNova AI is temporarily unavailable. Please try again.",
        )
    if isinstance(exc, asyncio.TimeoutError):
        _set_provider_state("provider_unavailable", 504, "timeout")
        return (
            504,
            "AI_REQUEST_DEADLINE_EXCEEDED",
            "EduNova AI is temporarily unavailable. Please try again.",
        )
    if isinstance(exc, LLMConfigurationError):
        _set_provider_state("missing_config", None, settings.llm_configuration_error or "missing_config")
        logger.error(
            "AI_PROVIDER_CONFIGURATION_ERROR provider=%s model=%s host=%s reason=%s",
            settings.llm_provider,
            settings.local_model_id if settings.is_local_llm else settings.llm_model,
            _provider_log_host(settings),
            settings.llm_configuration_error,
        )
        return 503, "LLM_MISSING_CONFIG", "EduNova AI is not configured correctly."
    if isinstance(exc, LLMResponseError):
        status = getattr(exc, "status_code", None)
        logger.error(
            "AI_PROVIDER_ERROR provider=%s model=%s host=%s status=%s type=%s",
            settings.llm_provider,
            settings.local_model_id if settings.is_local_llm else settings.llm_model,
            _provider_log_host(settings),
            status,
            error_type,
        )
        if error_type == "model_loading":
            _set_provider_state("model_loading", 503, error_type)
            return (
                503,
                "LLM_MODEL_LOADING",
                "EduNova AI is preparing its model — your question is queued and will be answered automatically.",
            )
        if error_type == "model_unavailable":
            _set_provider_state("model_unavailable", 503, error_type)
            report = model_manager.error_report if (model_manager is not None) else None
            if report:
                logger.error(
                    "MODEL_STARTUP_ERROR model=%s url=%s status=%s stage=%s reason=%s",
                    report.get("model"), report.get("url"), report.get("status"),
                    report.get("stage"), report.get("reason"),
                )
            return (
                503,
                "LLM_MODEL_UNAVAILABLE",
                getattr(exc, "provider_message", None) or "EduNova AI's self-hosted model could not start. It will retry automatically.",
            )
        if error_type == "model_busy":
            _set_provider_state("model_busy", 503, error_type)
            return 503, "LLM_MODEL_BUSY", "EduNova AI is finishing another request — you are next in the queue."
        if status in (401, 403):
            _set_provider_state("authentication_failed", status, error_type)
            return 503, "LLM_AUTHENTICATION_FAILED", "EduNova AI provider authentication is not configured correctly."
        if status == 404 or error_type in {"not_found", "model_not_found"}:
            _set_provider_state("model_not_found", status, error_type)
            return 503, "LLM_MODEL_NOT_FOUND", "The configured AI model is unavailable."
        if status == 429 or error_type == "rate_limit":
            _set_provider_state("rate_limited", 429, error_type)
            return 429, "LLM_RATE_LIMITED", "EduNova AI is rate limited. Please try again shortly."
        if status in (408, 504) or error_type == "timeout":
            _set_provider_state("provider_unavailable", status or 504, error_type)
            return 504, "LLM_TIMEOUT", "EduNova AI is temporarily unavailable. Please try again."
        if status == 400:
            _set_provider_state("provider_unavailable", status, error_type)
            return 502, "LLM_INVALID_REQUEST", "The AI provider rejected the request."
        _set_provider_state("provider_unavailable", status, error_type)
        return 502, "LLM_PROVIDER_UNAVAILABLE", "The AI model is temporarily unavailable. Please try again."
    logger.exception("Agent request failed")
    return 500, "LLM_INTERNAL_ERROR", "EduNova AI could not complete this request. Please try again."


async def _ready_gate() -> None:
    """Ensure the model is usable before any chat work; raises honest errors."""
    if settings.is_local_llm and model_manager is not None:
        await model_manager.wait_ready(timeout=settings.local_chat_wait_seconds)


async def _ready_gate_with_keepalive():
    """Wait for the model to become ready while streaming honest status.

    This is the AI-service-side request queue: when the model is still warming
    the caller receives a ``status`` event ("EduNova AI is preparing its model")
    followed by SSE keep-alive comments every 2 seconds until the model is
    READY, then control returns and the request is processed normally. The
    user's message is never dropped and they are never told to "try again
    shortly" — the queue keeps the request until the model is ready (or a hard
    deadline is exceeded).

    (The Express gateway performs the same wait against GET /api/ai/ready, so
    the browser sees this preparing state even when the AI service itself was
    scaled to zero and must cold-boot.)
    """
    if not settings.is_local_llm or model_manager is None:
        return

    # Already ready — fast path, no polling.
    if _model_is_ready():
        return

    preparing_payload = json.dumps(
        {
            "type": "status",
            "event": "model.preparing",
            "status": "preparing",
            "message": "EduNova AI is preparing its model — your question is queued. You don't need to do anything.",
        },
        ensure_ascii=False,
    )
    yield f"data: {preparing_payload}\n\n"

    deadline = time.monotonic() + settings.local_chat_wait_seconds
    last_state = _model_state_value()
    while time.monotonic() < deadline:
        if _model_is_ready():
            logger.info("[EduNova AI] Model became ready during keep-alive polling state=%s", last_state)
            return
        state = _model_state_value()
        if state == "error":
            raise LLMResponseError(
                "The self-hosted EduNova model failed to start",
                status_code=503,
                error_type="model_unavailable",
                provider_message=model_manager.last_error or "model load failed",
            )
        if state != last_state:
            logger.info("[EduNova AI] Model state transition %s -> %s", last_state, state)
            last_state = state
        # SSE comments (lines starting with ':') keep the TCP connection alive
        # so proxies never mistake a waiting request for a dead one.
        yield ": model-loading\n\n"
        await asyncio.sleep(2)

    # Hard deadline exceeded — a request cannot be held forever.
    raise LLMResponseError(
        "EduNova AI's model is still preparing after the maximum queue time",
        status_code=503,
        error_type="model_loading",
        provider_message=f"state={_model_state_value()} after {settings.local_chat_wait_seconds}s",
    )


async def _execute(
    request: ChatRequest,
    conversation,
    event_callback,
) -> dict[str, Any]:
    """Route to a deterministic fast path or the full autonomous agent loop."""
    decision = intent_router.classify(
        request.message,
        list(conversation.messages),
    )
    common = dict(
        goal=request.message.strip(),
        conversation=list(conversation.messages),
        conversation_id=conversation.id,
        user_id=str(request.owner_id or request.email or "authenticated-user"),
        user_role=str(request.user_role or "student"),
        user_name=str(request.user_name or "Student"),
        user_email=str(request.user_email or request.email or ""),
        application_context=request.application_context,
        event_callback=event_callback,
    )
    if decision.intent != "complex":
        logger.info(
            "[EduNova AI] ROUTE_SELECTED intent=%s tools=%s reason=%s",
            decision.intent, ",".join(decision.tools) or "-", decision.reason,
        )
        return await run_fast_path(
            settings=settings,
            llm=llm,
            registry=registry,
            decision=decision,
            **common,
        )
    logger.info("[EduNova AI] ROUTE_SELECTED intent=complex reason=%s", decision.reason)
    result = await agent.run(**common)
    return result.public()


async def _run_non_stream(request: ChatRequest) -> dict[str, Any]:
    started = time.monotonic()
    queue_started = started
    try:
        await _ready_gate()
    except Exception as exc:
        _bump_metric("error_count")
        raise
    queue_ms = int((time.monotonic() - queue_started) * 1000)
    _record_latency("queue_time_ms", queue_ms)
    logger.info(
        "[EduNova AI] MODEL_READY request_id=%s elapsed_ms=%s queue_ms=%s",
        request.request_id, _ms(started), queue_ms,
    )
    conversation = conversations.get_or_create(request.conversation_id, _owner(request))

    result = await _execute(request, conversation, None)
    conversations.append_turn(conversation, request.message.strip(), result.get("message", ""))
    _set_provider_state("ready" if not settings.is_local_llm else "model_ready", 200, None)
    total_ms = _ms(started)
    _record_latency("total_request_latency_ms", total_ms)
    _bump_metric("request_count")
    _bump_metric("success_count")
    logger.info(
        "[EduNova AI] RESPONSE_SENT request_id=%s total_ms=%s",
        request.request_id, total_ms,
    )
    return result


async def _stream(request: ChatRequest):
    started = time.monotonic()
    queue_started = started
    first_token_seen = False
    success_reported = False
    try:
        # Use keep-alive polling instead of a silent blocking gate. This emits a
        # status event ("preparing…") and keeps the connection alive while the
        # model finishes starting, so proxies never drop the request and the
        # student is never told to press Try Again.
        async for keepalive in _ready_gate_with_keepalive():
            yield keepalive
    except Exception as exc:
        status, code, message = _safe_error(exc)
        _bump_metric("error_count")
        yield "data: " + json.dumps(
            {
                "type": "error",
                "success": False,
                "status": status,
                "message": message,
                "error": {"code": code, "message": message},
                "agentStatus": "failed",
                "requestId": request.request_id,
            },
            ensure_ascii=False,
        ) + "\n\n"
        return

    queue_ms = int((time.monotonic() - queue_started) * 1000)
    _record_latency("queue_time_ms", queue_ms)
    logger.info(
        "[EduNova AI] MODEL_READY request_id=%s elapsed_ms=%s queue_ms=%s",
        request.request_id, _ms(started), queue_ms,
    )
    conversation = conversations.get_or_create(request.conversation_id, _owner(request))
    queue: asyncio.Queue[dict[str, Any] | None] = asyncio.Queue()

    async def event_callback(event: dict[str, Any]) -> None:
        await queue.put(event)

    async def runner() -> None:
        try:
            result = await _execute(request, conversation, event_callback)
            conversations.append_turn(conversation, request.message.strip(), result.get("message", ""))
            _set_provider_state("ready" if not settings.is_local_llm else "model_ready", 200, None)
            await queue.put({"type": "answer", **result})
        except Exception as exc:
            status, code, message = _safe_error(exc)
            _bump_metric("error_count")
            await queue.put(
                {
                    "type": "error",
                    "success": False,
                    "status": status,
                    "message": message,
                    "error": {"code": code, "message": message},
                    "agentStatus": "failed",
                    "conversationId": conversation.id,
                    "requestId": request.request_id,
                }
            )
        finally:
            await queue.put(None)

    task = asyncio.create_task(runner())
    try:
        while True:
            try:
                event = await asyncio.wait_for(queue.get(), timeout=5)
            except asyncio.TimeoutError:
                yield ": keep-alive\n\n"
                continue
            if event is None:
                break
            # Per-request + global metrics on the live event stream.
            if event.get("type") == "token" and isinstance(event.get("delta"), str):
                if not first_token_seen:
                    first_token_seen = True
                    first_ms = int((time.monotonic() - started) * 1000)
                    _record_latency("first_token_latency_ms", first_ms)
                    logger.info(
                        "[EduNova AI] FIRST_TOKEN request_id=%s first_token_ms=%s",
                        request.request_id, first_ms,
                    )
                _bump_metric("tokens_generated")
            if event.get("type") == "answer":
                success_reported = True
                _bump_metric("request_count")
                _bump_metric("success_count")
                _record_latency("total_request_latency_ms", int((time.monotonic() - started) * 1000))
            event.setdefault("requestId", request.request_id)
            yield "data: " + json.dumps(event, ensure_ascii=False) + "\n\n"
    finally:
        if not success_reported and not first_token_seen:
            # Request counted as failed only if nothing useful was delivered.
            pass
        if not task.done():
            task.cancel()
            try:
                await asyncio.wait_for(asyncio.shield(task), timeout=2)
            except (asyncio.TimeoutError, asyncio.CancelledError, Exception):
                pass


@app.post("/api/ai/chat")
async def chat(
    payload: ChatRequest,
    request: Request,
    x_ai_internal_token: str | None = Header(default=None),
):
    request_started = time.monotonic()
    request_id = str(request.headers.get("x-request-id") or _new_request_id())[:80]
    payload.request_id = request_id
    logger.info(
        "[EduNova AI] REQUEST_START request_id=%s stream=%s message_chars=%s runtime=%s",
        request_id, payload.stream, len(payload.message), settings.local_model_runtime,
    )
    _authorize_internal_request(x_ai_internal_token)
    logger.info("[EduNova AI] AUTH_COMPLETE request_id=%s elapsed_ms=%s", request_id, _ms(request_started))
    clean_message = payload.message.strip()
    if not clean_message:
        _bump_metric("error_count")
        raise HTTPException(status_code=422, detail="message cannot be blank")
    payload.message = clean_message

    # Response time is a performance metric, never a generation limit. The
    # self-hosted model runs to EOS (or its adaptive token budget) while SSE
    # keep-alives and real token events keep the connection active.

    wants_stream = payload.stream or "text/event-stream" in request.headers.get("accept", "")
    if wants_stream:
        return StreamingResponse(
            _stream(payload),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "X-Accel-Buffering": "no",
                "Connection": "keep-alive",
                "X-Request-Id": request_id,
            },
        )
    try:
        return await _run_non_stream(payload)
    except Exception as exc:
        status, code, message = _safe_error(exc)
        raise HTTPException(
            status_code=status,
            detail={"code": code, "message": message, "requestId": request_id},
        ) from exc


@app.post("/api/ai/query")
@app.post("/ai/query")
async def legacy_query(
    payload: ChatRequest,
    x_ai_internal_token: str | None = Header(default=None),
):
    _authorize_internal_request(x_ai_internal_token)
    payload.stream = False
    try:
        return await _run_non_stream(payload)
    except Exception as exc:
        status, code, message = _safe_error(exc)
        raise HTTPException(status_code=status, detail={"code": code, "message": message}) from exc
