"""FastAPI entrypoint for the EduNova unified autonomous AI agent.

EduNova AI is self-hosted by default: a quantized open-source GGUF model
(Qwen2.5-0.5B-Instruct by default) runs in-process through llama.cpp and acts
as the actual AI brain. No OpenAI/Groq/Gemini/Anthropic/OpenRouter calls are
made. Web search stays available as an external *data source*; every answer is
reasoned over and generated by the local model.
"""

from __future__ import annotations

import asyncio
from contextlib import asynccontextmanager
import json
import logging
import os
from pathlib import Path
import secrets
from typing import Any
from datetime import datetime, timezone
from urllib.parse import urlsplit

from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, ConfigDict, Field

# Local development convenience only. Production injects environment variables.
try:
    from dotenv import load_dotenv

    load_dotenv(Path(__file__).resolve().parent / ".env")
    load_dotenv(Path(__file__).resolve().parents[1] / "server" / ".env")
except ImportError:
    pass

from agent.engine import AgentEngine
from agent.llm import LLMConfigurationError, LLMResponseError
from agent.local_llm import create_llm, runtime_available, runtime_version
from agent.memory import ConversationStore
from agent.router import FAST_INTENTS, IntentRouter, run_fast_path
from agent.tools import ToolRegistry, build_all_tools
from config import load_settings

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
logger = logging.getLogger("edunova.api")
settings = load_settings()


# --- Safe startup diagnostics (no secrets) ---
def _log_startup_diagnostics() -> None:
    diag = settings.llm_safe_diagnostics()
    host = diag.get("llm_base_url_host") or "unknown"
    is_prod = os.getenv("NODE_ENV", "").lower() == "production" or os.getenv("ENV", "").lower() == "production"
    localhost_warning = ""
    if diag.get("llm_base_url_is_localhost") and is_prod and not settings.is_local_llm:
        localhost_warning = " [WARNING: base_url points to localhost in production]"
    logger.info(
        "AI_SERVICE_STARTUP llm_configured=%s provider=%s model=%s api_key_present=%s search_configured=%s internal_auth_required=%s%s",
        diag.get("llm_configured"),
        settings.llm_provider,
        diag.get("llm_model") or "none",
        diag.get("llm_api_key_present"),
        settings.search_configured,
        settings.ai_require_internal_token,
        localhost_warning,
    )
    if settings.is_local_llm:
        if settings.llm_configured:
            logger.info(
                "LOCAL_MODEL_STARTUP model=%s ctx=%s threads=%s preload=%s dir=%s",
                settings.local_model_id,
                settings.local_model_ctx_size,
                settings.local_model_threads,
                settings.local_preload_model,
                settings.local_model_dir,
            )
            # Requirement: the resolved download URL must be visible in the
            # production logs. It is sanitized (no credentials, no query) so it
            # is safe to print, and it is what makes a future 404 diagnosable
            # in one glance instead of a guessing game.
            logger.info(
                "LOCAL_MODEL_SOURCE url=%s expected_bytes=%s sha256_pinned=%s est_ram_mb=%s",
                settings.local_model_safe_url or "not-configured",
                settings.local_model_expected_size or "unknown",
                bool(settings.local_model_expected_sha256),
                settings.local_model_estimated_ram_mb or "unknown",
            )
            if not settings.local_model_known_entry and not settings.local_model_url:
                logger.warning(
                    "LOCAL_MODEL_NOT_IN_VERIFIED_CATALOGUE repo=%s file=%s "
                    "hint=The file existence/size/sha256 are not pre-verified; a wrong "
                    "LOCAL_MODEL_FILE will fail the startup preflight with HTTP 404.",
                    settings.local_model_repo,
                    settings.local_model_file,
                )
        else:
            logger.error(
                "LOCAL_MODEL_CONFIGURATION_INCOMPLETE reason=%s url=%s "
                "hint=Set LOCAL_MODEL_REPO/LOCAL_MODEL_FILE or LOCAL_MODEL_URL",
                settings.llm_configuration_error,
                settings.local_model_safe_url or "not-configured",
            )
        return
    if not settings.llm_configured:
        missing: list[str] = []
        if not settings.llm_api_key:
            missing.append("LLM_API_KEY")
        if not settings.llm_model:
            missing.append("LLM_MODEL")
        if not settings.llm_base_url:
            missing.append("LLM_BASE_URL")
        logger.warning(
            "AI_LLM_CONFIGURATION_INCOMPLETE missing=%s llm_key_present=%s llm_model_present=%s llm_base_url_present=%s "
            "hint=Self-hosted default: set LLM_PROVIDER=local (recommended) or legacy LLM_PROVIDER/LLM_API_KEY/LLM_MODEL/LLM_BASE_URL",
            ",".join(missing) if missing else "unknown",
            diag.get("llm_api_key_present"),
            diag.get("llm_model_present"),
            diag.get("llm_base_url_present"),
        )
    else:
        logger.info(
            "AI_PROVIDER_STARTUP_OK provider_host=%s model=%s timeout=%s json_mode=%s",
            host,
            settings.llm_model,
            settings.llm_timeout_seconds,
            settings.llm_json_mode,
        )


_log_startup_diagnostics()

registry = ToolRegistry(
    allowed_permissions={"READ_INTERNAL", "WRITE_INTERNAL", "READ_EXTERNAL", "UTILITY"}
)
for definition in build_all_tools(settings):
    registry.register(definition)

# Construction is lightweight; the GGUF model itself is downloaded and loaded
# in the background during the FastAPI lifespan (port binds immediately).
llm, model_manager = create_llm(settings)

agent = AgentEngine(settings, llm, registry)
intent_router = IntentRouter(settings)
provider_runtime = {
    "state": "ready" if settings.llm_configured else "missing_config",
    "lastCheckedAt": None,
    "lastHttpStatus": None,
    "lastErrorType": None,
}
if settings.is_local_llm:
    provider_runtime["state"] = "model_loading" if settings.local_preload_model else "cold"


def _provider_log_host(settings) -> str:
    """Where the completion physically came from, for logs.

    The local provider runs in-process, so echoing `llm_base_url` (a leftover
    external-API setting) would name a host that was never contacted.
    """
    if settings.is_local_llm:
        return "in-process:llama.cpp"
    try:
        return urlsplit(settings.llm_base_url).hostname or "none" if settings.llm_base_url else "none"
    except Exception:
        return "invalid"


def _set_provider_state(state: str, status: int | None = None, error_type: str | None = None) -> None:
    provider_runtime.update({
        "state": state,
        "lastCheckedAt": datetime.now(timezone.utc).isoformat(),
        "lastHttpStatus": status,
        "lastErrorType": error_type,
    })


conversations = ConversationStore(
    max_turns=settings.conversation_max_turns,
    ttl_seconds=settings.conversation_ttl_seconds,
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Bind the port first (Render health check passes), load the GGUF model in
    # the background. Chat requests meanwhile receive an honest 503
    # LLM_MODEL_LOADING which the Express API retries with backoff.
    if model_manager is not None and settings.local_preload_model:
        if not runtime_available():
            logger.error(
                "LOCAL_MODEL_RUNTIME_MISSING hint=llama-cpp-python is not importable; "
                "the AI service cannot run a self-hosted model. Reinstall "
                "ai_engine/requirements.txt (PIP_EXTRA_INDEX_URL provides prebuilt CPU wheels)."
            )
        else:
            logger.info("LOCAL_MODEL_RUNTIME runtime=llama-cpp-python version=%s", runtime_version())
        model_manager.ensure_loading()
    yield


app = FastAPI(
    title="EduNova AI Agent",
    version="3.0.0",
    description=(
        "Self-hosted unified data-aware learning and research agent: local quantized GGUF model "
        "reasoning over the EduNova database, web search, and conversation context."
    ),
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.cors_origins),
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "X-AI-Internal-Token"],
)


class ChatRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True, extra="ignore")

    message: str = Field(min_length=1, max_length=12_000)
    conversation_id: str | None = Field(default=None, alias="conversationId", max_length=100)
    owner_id: str | None = Field(default=None, alias="ownerId", max_length=200)
    user_role: str | None = Field(default="student", alias="userRole", max_length=50)
    user_name: str | None = Field(default="Student", alias="userName", max_length=100)
    user_email: str | None = Field(default=None, alias="userEmail", max_length=320)
    email: str | None = Field(default=None, max_length=320)  # Legacy client compatibility.
    application_context: dict[str, Any] = Field(default_factory=dict, alias="applicationContext")
    stream: bool = False


@app.get("/")
async def root() -> dict[str, Any]:
    return {
        "success": True,
        "service": "edunova-agent",
        "version": "3.0.0",
        "architecture": "self-hosted unified-data-aware agent (llama.cpp GGUF + ToolRegistry)",
        "endpoint": "POST /api/ai/chat",
    }


def _model_health_block(include_source: bool = False) -> dict[str, Any]:
    if model_manager is None:
        return {}
    return {"model": model_manager.snapshot(include_source=include_source)}


def _readiness() -> dict[str, Any]:
    """The four facts requirement 11 asks a health check to confirm."""
    if not settings.is_local_llm or model_manager is None:
        return {
            "modelFileExists": None,
            "runtimeAvailable": None,
            "modelInitialized": provider_runtime["state"] == "ready",
            "inferenceAvailable": provider_runtime["state"] == "ready",
        }
    snap = model_manager.snapshot()
    return {
        "modelFileExists": bool(snap.get("fileExists")),
        "runtimeAvailable": bool(snap.get("runtimeAvailable")),
        "modelInitialized": snap.get("state") == "ready",
        "inferenceAvailable": bool(snap.get("inferenceAvailable")),
    }


@app.get("/health")
async def health() -> dict[str, Any]:
    """Liveness for the platform health check.

    Deliberately reports ``status: live`` as soon as the port is bound (Render
    would otherwise kill the service while the weights download), but the model
    readiness is reported honestly next to it so nothing downstream can claim
    "ready" while the model is still starting.
    """
    diag = settings.llm_safe_diagnostics()
    readiness = _readiness()
    payload = {
        "status": "live",
        "service": "edunova-agent",
        # For the self-hosted provider the live state is the model manager's
        # state machine (downloading/loading/ready/error), not a cached probe.
        "providerState": (model_manager.state if (settings.is_local_llm and model_manager) else provider_runtime["state"]),
        "modelReady": bool(readiness["modelInitialized"] and readiness["inferenceAvailable"]),
        "readiness": readiness,
        "provider": settings.llm_provider,
        "selfHosted": settings.is_local_llm,
        "llmConfigured": settings.llm_configured,
        "llmDiagnostics": diag,
        "webSearchConfigured": settings.search_configured,
        "internalAuthConfigured": bool(settings.ai_internal_token),
        "internalAuthRequired": settings.ai_require_internal_token,
        "tools": [spec["name"] for spec in registry.specs()],
        "fastPathIntents": sorted(FAST_INTENTS),
        "limits": {
            "maxIterations": settings.max_agent_iterations,
            "maxToolCalls": settings.max_tool_calls,
            "maxRuntimeSeconds": settings.max_agent_runtime_seconds,
        },
    }
    payload.update(_model_health_block())
    return payload


@app.get("/api/ai/health")
async def ai_health(
    x_ai_internal_token: str | None = Header(default=None),
    deep: bool = False,
) -> dict[str, Any]:
    """Real health check for the model.

    Confirms, in this order: the runtime is importable, the model file exists,
    the model initialized, and inference is available. ``?deep=true`` proves
    the last point by generating a handful of real tokens instead of trusting
    the state machine.
    """
    _authorize_internal_request(x_ai_internal_token)
    probe_state = "skipped"
    probe_error: str | None = None
    probe_detail: dict[str, Any] | None = None
    if deep or not settings.is_local_llm:
        try:
            if settings.is_local_llm and model_manager is not None:
                await llm.probe(deep=True)
                probe_detail = {"inference": "verified"}
            else:
                await llm.probe()
            probe_state = "ready"
            if not settings.is_local_llm:
                _set_provider_state("ready", 200, None)
        except Exception as exc:
            probe_state = "error"
            probe_error = getattr(exc, "error_type", None) or exc.__class__.__name__
            if settings.is_local_llm:
                _set_provider_state(
                    "model_loading" if probe_error == "model_loading" else "model_unavailable",
                    503,
                    probe_error,
                )
            else:
                _safe_error(exc)
    readiness = _readiness()
    if settings.is_local_llm:
        model_ready = (
            model_manager is not None
            and model_manager.state == "ready"
            and (probe_state != "error")
        )
        model_status = model_manager.state if model_manager is not None else "missing_manager"
    else:
        model_ready = provider_runtime["state"] == "ready"
        model_status = provider_runtime["state"]
    payload: dict[str, Any] = {
        "success": model_ready,
        "status": model_status,
        # Single field the UI keys off: only "ready" may render "Ready to help".
        "modelState": model_status,
        "modelReady": model_ready,
        "readiness": readiness,
        "serviceAvailable": True,
        "configured": settings.llm_configured,
        "provider": settings.llm_provider,
        "selfHosted": settings.is_local_llm,
        "model": settings.local_model_id if settings.is_local_llm else settings.llm_model,
        "apiKeyPresent": bool(settings.llm_api_key),
        "configurationError": settings.llm_configuration_error,
        "probe": probe_state,
        "probeError": probe_error,
        "probeDetail": probe_detail,
        "lastCheckedAt": provider_runtime["lastCheckedAt"],
        "lastProviderHttpStatus": provider_runtime["lastHttpStatus"],
        "lastProviderErrorType": provider_runtime["lastErrorType"],
    }
    payload.update(_model_health_block(include_source=True))
    return payload


@app.get("/api/ai/model/source-check")
async def model_source_check(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    """Verify the configured model URL is really downloadable (HEAD only).

    This is the operator tool for the failure that caused this incident: it
    answers "does LOCAL_MODEL_FILE actually exist?" without downloading 380MB
    and without restarting the service.
    """
    _authorize_internal_request(x_ai_internal_token)
    if not settings.is_local_llm or model_manager is None:
        return {"success": False, "reason": "not_local_provider", "provider": settings.llm_provider}
    try:
        check = await model_manager.preflight()
        return {
            "success": True,
            "model": settings.local_model_id,
            "url": settings.local_model_safe_url,
            **check,
        }
    except Exception as exc:
        report = getattr(exc, "report", None)
        return {
            "success": False,
            "model": settings.local_model_id,
            "url": settings.local_model_safe_url,
            "error": report() if callable(report) else {"reason": str(exc)[:200]},
        }


@app.get("/api/ai/diagnostics")
async def diagnostics(
    x_ai_internal_token: str | None = Header(default=None),
) -> dict[str, Any]:
    _authorize_internal_request(x_ai_internal_token)
    diag = settings.llm_safe_diagnostics()
    host = diag.get("llm_base_url_host") or "unknown"
    base_url_ok = bool(host and host != "unknown" and "." in host)
    return {
        "success": True,
        "service": "edunova-agent",
        "llm": diag,
        "baseUrlResolvable": base_url_ok,
        "note": (
            "Self-hosted local model by default (LLM_PROVIDER=local); no external LLM API key is required. "
            "Legacy providers remain available behind explicit LLM_PROVIDER=openai[_compatible] configuration."
        ),
    }


def _authorize_internal_request(token: str | None) -> None:
    if settings.ai_require_internal_token and not settings.ai_internal_token:
        raise HTTPException(
            status_code=503,
            detail="AI internal authentication is required but not configured",
        )
    if settings.ai_internal_token and not secrets.compare_digest(
        str(token or ""), settings.ai_internal_token
    ):
        raise HTTPException(status_code=401, detail="AI service authorization failed")


def _owner(request: ChatRequest) -> str:
    return str(request.owner_id or request.email or "anonymous")[:200]


def _sanitize_provider_message_for_user(text: str, limit: int = 180) -> str:
    import re

    t = str(text or "").strip()
    if not t:
        return ""
    t = re.sub(r"<[^>]*>", " ", t)
    t = re.sub(r"\s+", " ", t).strip()
    t = re.sub(r"sk-[A-Za-z0-9-_]{10,}", "[redacted]", t)
    if len(t) > limit:
        t = t[:limit].rstrip() + "…"
    return t


def _safe_error(exc: Exception) -> tuple[int, str, str]:
    error_type = str(getattr(exc, "error_type", "") or "")
    # Local self-hosted model states: surface honest, structured states and
    # never substitute a canned/fake answer.
    if error_type == "model_loading":
        _set_provider_state("model_loading", 503, error_type)
        return (
            503,
            "LLM_MODEL_LOADING",
            "EduNova AI is starting its self-hosted model (downloading/loading weights). Please try again shortly.",
        )
    if error_type == "model_unavailable":
        _set_provider_state("model_unavailable", 503, error_type)
        # Full, structured diagnostics stay in the backend log (they name the
        # model, the URL and the HTTP status). The browser gets a clean,
        # non-technical sentence — never a raw provider/download error string.
        report = model_manager.error_report if (model_manager is not None) else None
        if report:
            logger.error(
                "MODEL_STARTUP_ERROR model=%s url=%s status=%s stage=%s reason=%s",
                report.get("model"),
                report.get("url"),
                report.get("status"),
                report.get("stage"),
                report.get("reason"),
            )
        else:
            logger.error(
                "MODEL_STARTUP_ERROR model=%s url=%s reason=%s",
                settings.local_model_id,
                settings.local_model_safe_url,
                _sanitize_provider_message_for_user(getattr(exc, "provider_message", "")),
            )
        permanent = bool(report.get("permanent")) if report else False
        if permanent:
            return (
                503,
                "LLM_MODEL_UNAVAILABLE",
                "EduNova AI's self-hosted model is not available on the server. "
                "An administrator needs to check the AI service model configuration.",
            )
        return (
            503,
            "LLM_MODEL_UNAVAILABLE",
            "EduNova AI's self-hosted model could not start. It will retry automatically — "
            "please try again in a moment.",
        )
    if isinstance(exc, asyncio.TimeoutError):
        _set_provider_state("provider_unavailable", 504, "timeout")
        return 504, "LLM_TIMEOUT", "EduNova AI took too long to respond. Please try again."
    if isinstance(exc, LLMConfigurationError):
        _set_provider_state("missing_config", None, settings.llm_configuration_error or "missing_config")
        logger.error(
            "AI_PROVIDER_CONFIGURATION_ERROR provider=%s model=%s host=%s reason=%s",
            settings.llm_provider,
            settings.local_model_id if settings.is_local_llm else settings.llm_model,
            _provider_log_host(settings),
            settings.llm_configuration_error,
        )
        return 503, "LLM_MISSING_CONFIG", "EduNova AI is not configured correctly."
    if isinstance(exc, LLMResponseError):
        status = getattr(exc, "status_code", None)
        logger.error(
            "AI_PROVIDER_ERROR provider=%s model=%s host=%s status=%s type=%s",
            settings.llm_provider,
            settings.local_model_id if settings.is_local_llm else settings.llm_model,
            _provider_log_host(settings),
            status,
            error_type,
        )
        if status in (401, 403):
            _set_provider_state("authentication_failed", status, error_type)
            return 503, "LLM_AUTHENTICATION_FAILED", "EduNova AI provider authentication is not configured correctly."
        if status == 404 or error_type in {"not_found", "model_not_found"}:
            _set_provider_state("model_not_found", status, error_type)
            return 503, "LLM_MODEL_NOT_FOUND", "The configured AI model is unavailable."
        if status == 429 or error_type == "rate_limit":
            _set_provider_state("rate_limited", 429, error_type)
            return 429, "LLM_RATE_LIMITED", "EduNova AI is rate limited. Please try again shortly."
        if status in (408, 504) or error_type == "timeout":
            _set_provider_state("provider_unavailable", status or 504, error_type)
            return 504, "LLM_TIMEOUT", "EduNova AI took too long to respond. Please try again."
        if status == 400:
            _set_provider_state("provider_unavailable", status, error_type)
            return 502, "LLM_INVALID_REQUEST", "The AI provider rejected the request."
        _set_provider_state("provider_unavailable", status, error_type)
        return 502, "LLM_PROVIDER_UNAVAILABLE", "The AI model is temporarily unavailable. Please try again."
    logger.exception("Agent request failed")
    return 500, "LLM_INTERNAL_ERROR", "EduNova AI could not complete this request. Please try again."


async def _ready_gate() -> None:
    """Ensure the model is usable before any chat work; raises honest errors."""
    if settings.is_local_llm and model_manager is not None:
        await model_manager.wait_ready(timeout=settings.local_chat_wait_seconds)


async def _execute(
    request: ChatRequest,
    conversation,
    event_callback,
) -> dict[str, Any]:
    """Route to a deterministic fast path or the full autonomous agent loop."""
    decision = intent_router.classify(
        request.message,
        list(conversation.messages),
    )
    common = dict(
        goal=request.message.strip(),
        conversation=list(conversation.messages),
        conversation_id=conversation.id,
        user_id=str(request.owner_id or request.email or "authenticated-user"),
        user_role=str(request.user_role or "student"),
        user_name=str(request.user_name or "Student"),
        user_email=str(request.user_email or request.email or ""),
        application_context=request.application_context,
        event_callback=event_callback,
    )
    if decision.intent != "complex":
        logger.info("AGENT_ROUTE intent=%s reason=%s", decision.intent, decision.reason)
        return await run_fast_path(
            settings=settings,
            llm=llm,
            registry=registry,
            decision=decision,
            **common,
        )
    logger.info("AGENT_ROUTE intent=complex reason=%s", decision.reason)
    result = await agent.run(**common)
    return result.public()


async def _run_non_stream(request: ChatRequest) -> dict[str, Any]:
    await _ready_gate()
    conversation = conversations.get_or_create(request.conversation_id, _owner(request))
    result = await asyncio.wait_for(
        _execute(request, conversation, None),
        timeout=settings.max_agent_runtime_seconds,
    )
    conversations.append_turn(conversation, request.message.strip(), result.get("message", ""))
    _set_provider_state("ready" if not settings.is_local_llm else "model_ready", 200, None)
    return result


async def _stream(request: ChatRequest):
    try:
        await _ready_gate()
    except Exception as exc:
        status, code, message = _safe_error(exc)
        yield "data: " + json.dumps(
            {
                "type": "error",
                "success": False,
                "status": status,
                "message": message,
                "error": {"code": code, "message": message},
                "agentStatus": "failed",
            },
            ensure_ascii=False,
        ) + "\n\n"
        return

    conversation = conversations.get_or_create(request.conversation_id, _owner(request))
    queue: asyncio.Queue[dict[str, Any] | None] = asyncio.Queue()

    async def event_callback(event: dict[str, Any]) -> None:
        await queue.put(event)

    async def runner() -> None:
        try:
            result = await asyncio.wait_for(
                _execute(request, conversation, event_callback),
                timeout=settings.max_agent_runtime_seconds,
            )
            conversations.append_turn(conversation, request.message.strip(), result.get("message", ""))
            _set_provider_state("ready" if not settings.is_local_llm else "model_ready", 200, None)
            await queue.put({"type": "answer", **result})
        except Exception as exc:
            status, code, message = _safe_error(exc)
            await queue.put(
                {
                    "type": "error",
                    "success": False,
                    "status": status,
                    "message": message,
                    "error": {"code": code, "message": message},
                    "agentStatus": "failed",
                    "conversationId": conversation.id,
                }
            )
        finally:
            await queue.put(None)

    task = asyncio.create_task(runner())
    try:
        while True:
            try:
                event = await asyncio.wait_for(queue.get(), timeout=15)
            except asyncio.TimeoutError:
                yield ": keep-alive\n\n"
                continue
            if event is None:
                break
            yield "data: " + json.dumps(event, ensure_ascii=False) + "\n\n"
    finally:
        if not task.done():
            task.cancel()


@app.post("/api/ai/chat")
async def chat(
    payload: ChatRequest,
    request: Request,
    x_ai_internal_token: str | None = Header(default=None),
):
    _authorize_internal_request(x_ai_internal_token)
    clean_message = payload.message.strip()
    if not clean_message:
        raise HTTPException(status_code=422, detail="message cannot be blank")
    payload.message = clean_message

    wants_stream = payload.stream or "text/event-stream" in request.headers.get("accept", "")
    if wants_stream:
        return StreamingResponse(
            _stream(payload),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache, no-transform",
                "X-Accel-Buffering": "no",
                "Connection": "keep-alive",
            },
        )
    try:
        return await _run_non_stream(payload)
    except Exception as exc:
        status, code, message = _safe_error(exc)
        raise HTTPException(status_code=status, detail={"code": code, "message": message}) from exc


@app.post("/api/ai/query")
@app.post("/ai/query")
async def legacy_query(
    payload: ChatRequest,
    x_ai_internal_token: str | None = Header(default=None),
):
    _authorize_internal_request(x_ai_internal_token)
    payload.stream = False
    try:
        return await _run_non_stream(payload)
    except Exception as exc:
        status, code, message = _safe_error(exc)
        raise HTTPException(status_code=status, detail={"code": code, "message": message}) from exc
