#!/usr/bin/env node
/**
 * EduNova_X — Secret Extractor
 * ----------------------------
 * Automatically pulls MONGO_URI, JWT_SECRET, email credentials, and the
 * frontend TURN variables from the local .env files and formats them for:
 *   1. scripts/deploy/.env.secrets  (consumed by master-deploy.{sh,ps1})
 *   2. Render Blueprint envVars     (YAML snippet, printed to stdout)
 *   3. Vercel project env           (JSON snippet, printed to stdout)
 *
 * Usage:
 *   node scripts/deploy/extract-secrets.mjs
 *   ./scripts/deploy/extract-secrets.sh        (bash wrapper)
 *
 * It never overwrites existing VERCEL_TOKEN / RENDER_API_KEY / GIT_REPO values
 * already present in scripts/deploy/.env.secrets — only the values that are
 * missing or sourced from the .env files are (re)written.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";
import crypto from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..");
const SERVER_ENV = join(REPO_ROOT, "server", ".env");
const FRONTEND_ENV = join(REPO_ROOT, "frontend", ".env");
const SECRETS_FILE = join(__dirname, ".env.secrets");

/** Parse a dotenv file into an object. Values may contain '#' (e.g. Mongo URIs). */
function parseEnv(file) {
  const out = {};
  if (!existsSync(file)) return out;
  for (const rawLine of readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/** Quote a value for a KEY=VALUE secrets file when it needs it. */
function quote(value) {
  const v = String(value ?? "");
  if (/[\s#"']/.test(v)) return `"${v.replace(/"/g, '\\"')}"`;
  return v;
}

/** Preserve already-configured values from an existing .env.secrets. */
function readSecrets() {
  const out = {};
  if (existsSync(SECRETS_FILE)) {
    for (const line of readFileSync(SECRETS_FILE, "utf8").split(/\r?\n/)) {
      const t = line.trim();
      if (!t || t.startsWith("#")) continue;
      const eq = t.indexOf("=");
      if (eq <= 0) continue;
      const key = t.slice(0, eq).trim();
      let value = t.slice(eq + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      out[key] = value;
    }
  }
  return out;
}

const serverEnv = parseEnv(SERVER_ENV);
const frontendEnv = parseEnv(FRONTEND_ENV);
const existing = readSecrets();

const JWT = existing.JWT_SECRET || serverEnv.JWT_SECRET;
const ADMIN_PW =
  existing.ADMIN_TEMP_PASSWORD ||
  serverEnv.ADMIN_TEMP_PASSWORD ||
  crypto.randomBytes(24).toString("base64url");

const secrets = {
  // Tokens — never auto-filled; keep whatever you already configured.
  VERCEL_TOKEN: existing.VERCEL_TOKEN || "", // Vercel access token
  RENDER_API_KEY: existing.RENDER_API_KEY || "", // Render API key (rnd_...)
  GIT_REPO:
    existing.GIT_REPO || "https://github.com/ranjitacharya13-crypto/edunova_x",
  GIT_BRANCH: existing.GIT_BRANCH || "main",

  // Backend secrets (auto-extracted from server/.env)
  MONGO_URI: existing.MONGO_URI || serverEnv.MONGO_URI || "",
  JWT_SECRET: JWT || "",
  ADMIN_TEMP_PASSWORD: ADMIN_PW,
  EMAIL_USER: existing.EMAIL_USER || serverEnv.EMAIL_USER || "",
  EMAIL_PASS: existing.EMAIL_PASS || serverEnv.EMAIL_PASS || "",
  CONTACT_RECEIVER_EMAIL:
    existing.CONTACT_RECEIVER_EMAIL || serverEnv.CONTACT_RECEIVER_EMAIL || "",
  SEED_DEMO_USERS: existing.SEED_DEMO_USERS || "true",

  // TURN server (video on 4G/mobile) — auto-extracted from frontend/.env
  VITE_TURN_URL: existing.VITE_TURN_URL || frontendEnv.VITE_TURN_URL || "",
  VITE_TURN_USERNAME:
    existing.VITE_TURN_USERNAME || frontendEnv.VITE_TURN_USERNAME || "",
  VITE_TURN_CREDENTIAL:
    existing.VITE_TURN_CREDENTIAL || frontendEnv.VITE_TURN_CREDENTIAL || "",
  VITE_ICE_SERVERS_JSON:
    existing.VITE_ICE_SERVERS_JSON || frontendEnv.VITE_ICE_SERVERS_JSON || "",
};

const header = `# =============================================================================
# EduNova_X deploy secrets — auto-generated by extract-secrets.mjs
# (values for MONGO_URI/JWT/EMAIL/TURN were pulled from server/.env and
#  frontend/.env). This file is gitignored — NEVER commit it.
# Fill in the two TOKENS below, then run master-deploy.{sh,ps1}.
# =============================================================================
`;

const body = [
  "VERCEL_TOKEN=" + quote(secrets.VERCEL_TOKEN),
  "RENDER_API_KEY=" + quote(secrets.RENDER_API_KEY),
  "",
  "# --- Repo / branch ---",
  "GIT_REPO=" + quote(secrets.GIT_REPO),
  "GIT_BRANCH=" + quote(secrets.GIT_BRANCH),
  "",
  "# --- Backend secrets (from server/.env) ---",
  "MONGO_URI=" + quote(secrets.MONGO_URI),
  "JWT_SECRET=" + quote(secrets.JWT_SECRET),
  "ADMIN_TEMP_PASSWORD=" + quote(secrets.ADMIN_TEMP_PASSWORD),
  "EMAIL_USER=" + quote(secrets.EMAIL_USER),
  "EMAIL_PASS=" + quote(secrets.EMAIL_PASS),
  "CONTACT_RECEIVER_EMAIL=" + quote(secrets.CONTACT_RECEIVER_EMAIL),
  "SEED_DEMO_USERS=" + quote(secrets.SEED_DEMO_USERS),
  "",
  "# --- TURN server (video on 4G/mobile / strict NAT) — from frontend/.env ---",
  "VITE_TURN_URL=" + quote(secrets.VITE_TURN_URL),
  "VITE_TURN_USERNAME=" + quote(secrets.VITE_TURN_USERNAME),
  "VITE_TURN_CREDENTIAL=" + quote(secrets.VITE_TURN_CREDENTIAL),
  secrets.VITE_ICE_SERVERS_JSON
    ? "VITE_ICE_SERVERS_JSON=" + quote(secrets.VITE_ICE_SERVERS_JSON)
    : "# VITE_ICE_SERVERS_JSON=",
  "",
].join("\n");

writeFileSync(SECRETS_FILE, header + body);
console.log(`[OK] Wrote ${SECRETS_FILE}`);

// ---- Print Render Blueprint envVars (YAML) -------------------------------
const renderKeys = [
  "MONGO_URI",
  "JWT_SECRET",
  "ADMIN_TEMP_PASSWORD",
  "EMAIL_USER",
  "EMAIL_PASS",
  "CONTACT_RECEIVER_EMAIL",
  "CORS_ORIGINS",
];
const renderSnippet = renderKeys
  .filter((k) => secrets[k])
  .map((k) => `      - key: ${k}\n        sync: false`)
  .join("\n");

// ---- Print Vercel project env (JSON) --------------------------------------
const vercelKeys = [
  "VITE_API_URL", // set to https://<your-api>.onrender.com/api after deploy
  "VITE_SIGNAL_URL", // set to https://<your-signal>.onrender.com after deploy
  "VITE_API_PORT",
  "VITE_SIGNAL_PORT",
  "VITE_TURN_URL",
  "VITE_TURN_USERNAME",
  "VITE_TURN_CREDENTIAL",
  "VITE_ICE_SERVERS_JSON",
];
const vercelEnv = {};
for (const k of vercelKeys) {
  if (secrets[k]) vercelEnv[k] = secrets[k];
}

console.log("\n=== Render Blueprint envVars (paste under edunova-api) ===\n");
console.log(renderSnippet || "      # no extra secrets needed");
console.log("\n=== Vercel project env (Project Settings > Environment Variables) ===\n");
console.log(JSON.stringify(vercelEnv, null, 2));

const missing = ["MONGO_URI", "JWT_SECRET"].filter((k) => !secrets[k]);
if (missing.length) {
  console.warn(
    `\n[WARN] Missing values for: ${missing.join(", ")} — server/.env not found or incomplete.`,
  );
}
