"""Special tokens. Changing this set after a production release is a major version."""

SPECIAL_TOKENS = [
    "<pad>",
    "<bos>",
    "<eos>",
    "<unk>",
    "<user>",
    "</user>",
    "<assistant>",
    "</assistant>",
    "<system>",
    "</system>",
    "<tool>",
    "</tool>",
    "<context>",
    "</context>",
    "<untrusted>",
    "</untrusted>",
    "<json>",
    "</json>",
]

# Structured output markers the model is trained to emit.
STRUCTURE_TOKENS = [
    "FINAL_ANSWER",
    "TOOL_CALL",
    "TOOL_RESULT",
    "SEARCH_REQUEST",
    "QUIZ",
    "STUDY_PLAN",
    "AR_SCENE",
    "SUMMARY",
    "ERROR",
    "NEED_MORE_INFORMATION",
    "NO_RELEVANT_CONTEXT",
    "WEB_SEARCH_UNAVAILABLE",
    "TOOL_ERROR",
]

# Must stay 1:1 with TOOL_NAMES (except the "none" routing class). A missing
# atomic token gives that tool a length/byte-split disadvantage at decode time.
TOOL_TOKENS = [
    "get_student_profile",
    "get_subjects",
    "get_timetable",
    "get_today_schedule",
    "get_upcoming_classes",
    "get_syllabus",
    "get_learning_materials",
    "get_progress",
    "get_study_history",
    "get_quiz_history",
    "get_quiz_results",
    "get_assignments",
    "get_exams",
    "get_attendance",
    "get_notes",
    "get_goals",
    "get_upcoming_events",
    "get_notifications",
    "retrieve_learning_materials",
    "web_search",
    "open_url",
    "extract_webpage",
    "calculator",
    "get_current_datetime",
    "get_ar_lessons",
    "create_quiz",
    "save_quiz",
    "create_study_plan",
    "open_feature",
]

# Atomic JSON scaffolding tokens (added in edunova-tok-v2). The v1 byte
# encoder never emitted multi-character tokens, so the decoder had to spell
# `{"type":"TOOL_CALL",...}` byte-by-byte. v2 encodes these atomically.
JSON_WRAPPER_TOKENS = [
    '{"type":"',
    '","tool":"',
    '","arguments":',
    '","answer":"',
    '","query":"',
    '","subject":"',
    '{"',
    '":"',
    '","',
    '":{',
    '"}',
    '":[',
    '"]',
    '}}',
]

JSON_FIELD_TOKENS = [
    '"type"',
    '"tool"',
    '"arguments"',
    '"answer"',
    '"query"',
    '"subject"',
    '"unit"',
    '"count"',
    '"difficulty"',
    '"title"',
    '"questions"',
    '"question"',
    '"options"',
    '"answerIndex"',
    '"explanation"',
    '"topic"',
    '"objects"',
    '"name"',
    '"position"',
    '"description"',
    '"connections"',
    '"from"',
    '"to"',
    '"interactions"',
    '"schedule"',
    '"day"',
    '"time"',
    '"task"',
    '"message"',
    '"url"',
    '"expression"',
    '"view"',
]

EDU_TERMS = [
    "syllabus",
    "attendance",
    "timetable",
    "exam",
    "quiz",
    "assignment",
    "unit",
    "chapter",
    "semester",
    "CBSE",
    "ICSE",
    "NCERT",
    "JEE",
    "NEET",
    "board exam",
    "data structures",
    "algorithm",
    "photosynthesis",
    "Newton",
    "algebra",
    "calculus",
    "Hindi",
    "Tamil",
    "Marathi",
    "Bengali",
    "Telugu",
    "Kannada",
    "Gujarati",
    "Punjabi",
]
